### PR TITLE
Use progressbar from rich

### PR DESCRIPTION
**Pull request by glensc**
Found that `tqdm` has a proxy to render progressbar via rich library.

[asciicast](https://asciinema.org/a/ZMugng5EMksDQhQ6ebJ8xNYOU)

This differs from https://github.com/Taxel/PlexTraktSync/pull/271 that code changes are not necessary, just change the import.

### CODE REVIEW

**Comment by mcdallas** [comment]
Should this perhaps be an optional dependency? Like pip install plextraktsync[rich] if you want the fancy progressbar and catch the import error and use the basic one if rich is missing. https://stackoverflow.com/a/43090648/8040498

**Comment by glensc** [comment]
Some more fun,

```diff
-            from tqdm import tqdm
+            from tqdm.contrib.telegram import tqdm
```

And setting up the bot, like described here:
- https://github.com/tqdm/tqdm/blob/v4.62.1/tqdm/contrib/telegram.py#L97-L101

and environment:
- https://github.com/tqdm/tqdm/blob/v4.62.1/tqdm/contrib/telegram.py#L122-L123

```
export TQDM_TELEGRAM_CHAT_ID=''
export TQDM_TELEGRAM_TOKEN=''
```

Makes progressbar also appear on Telegram chat :D

image

**Comment by glensc** [comment]
@mcdallas well, the pip not finished:
- https://github.com/Taxel/PlexTraktSync/pull/263

I don't like that have to maintain `__version__` manually, so therefore not merged.

but I'd be ok if CI does the magic and pushes to pypi.

**Comment by glensc** [comment]
@mcdallas yeah, I'm not sure either how to handle this, it does look fancy! ;)

the extra dependencies aren't that big to worry about, and bundling makes things easier for users.

before:
```
[~/scm/plex/PlexTraktSync (main)★] ➔ du .direnv/python-3.9/lib/python3.9/site-packages/ -s
24M	.direnv/python-3.9/lib/python3.9/site-packages/
```

after:
```
[~/scm/plex/PlexTraktSync (tqdm-rick)★] ➔ du .direnv/python-3.9/lib/python3.9/site-packages/ -s
34M	.direnv/python-3.9/lib/python3.9/site-packages/
```

at least with pipenv installs it's weird that everything is locked, but still need to install something manually. for pip users pip install rich maybe even makes sense.

I'll just let it stay around here for a while to collect ideas.

**Comment by glensc** [comment]
¯\_(ツ)_/¯

**Comment by Hebusing** [comment]
> Some more fun,
> 
> ```diff
> -            from tqdm import tqdm
> +            from tqdm.contrib.telegram import tqdm
> ```
> 
> And setting up the bot, like described here:
> 
> * https://github.com/tqdm/tqdm/blob/v4.62.1/tqdm/contrib/telegram.py#L97-L101
> 
> and environment:
> 
> * https://github.com/tqdm/tqdm/blob/v4.62.1/tqdm/contrib/telegram.py#L122-L123
> 
> ```
> export TQDM_TELEGRAM_CHAT_ID=''
> export TQDM_TELEGRAM_TOKEN=''
> ```
> 
> Makes progressbar also appear on Telegram chat :D
> 
> image

@glensc: would you explain me how you've setup Telegram in PlexTraktSync to send you the logs in a chat please? I've already got a Telegram Bot, Chat ID and Token, so only the configuration in PlexTraktSync is needed. I looked into config.json but can't find those parameters TQDM_TELEGRAM_TOKEN and TQDM_TELEGRAM_CHAT_ID, and not sure what to do.
I'm sorry but I know nothing in Python...
Thank you!

**Comment by glensc** [comment]
TQDM_TELEGRAM_TOKEN, TQDM_TELEGRAM_CHAT_ID are environment variables. you set them before starting the script. you even copied the "export" lines in your reply!

**Comment by Hebusing** [comment]
@glensc, apologies in advance for asking you some more details...
I've edited __init__.py and added at the beginning of it:
```
import os
os.environ['TQDM_TELEGRAM_TOKEN'] = "my_long_private_token"
os.environ['TQDM_TELEGRAM_CHAT_ID'] = "my_chat_ID"

```
I ran the script but received nothing in my Telegram chat... Should I do anything else? :-|

**Comment by glensc** [comment]
Don't know, you could modify these lines directly:
- https://github.com/tqdm/tqdm/blob/v4.62.1/tqdm/contrib/telegram.py#L122-L123

**Comment by glensc** [comment]
You may find better luck in `tqdm` or `telegram` forums.

**Comment by Hebusing** [comment]
It worked... I didn't made the update in factory.py as you wrote. My bad!

Could it be possible in a next release to have those parameters when we build the docker container?
Like: 
TELEGRAM_NOTIFICATION = True/False
TELEGRAM_CHAT_ID = 'Your_long_private_key'
TELEGRAM_TOKEN = 'Your_token'

Thank you again for the work you do!!!

**Comment by twolaw** [comment]
This telegram discussion deserves a dedicated issue imho.
@Hebusing Could you copy/paste your last comment in a new issue please ?

**Comment by glensc** [comment]
@twolaw you rejected the issue last time:
- https://github.com/Taxel/PlexTraktSync/issues/109

but yes, the discussion telegram under merged pull request is very wrong place.

**Pull request merged**
