### PR TITLE
Refactor: Add requests_cache module wrapper

### PR DESCRIPTION
**Pull request by glensc**
Extracted from https://github.com/Taxel/PlexTraktSync/pull/122 making it smaller.

### CODE REVIEW

**Review by twolaw — COMMENTED** [review]
Ok for `trakt_cache` in _path.py_ but I don't see the point of _requests_cache.py_.
Too much factoring IMO.

**Comment by glensc** [comment]
Can't pull more changes from https://github.com/Taxel/PlexTraktSync/pull/122 as it would require other changes well (`@nocache` decorator), which I prefer to submit separately.

**Comment by glensc** [comment]
The whole global symbols modification is a bad design, but it takes some more iterations to re-design it better:

- logging should be an instance
- CONFIG should be an instance
- this requests_cache should be an instance

I'll turn this back to Draft as merge conflicts appeared, and maybe delay this module introduction for now.

**Comment by glensc** [comment]
Difficult to rebase other branches, as they depend on his change.

If this sill bothers after refactorings can submit another PR to deal with that.

**Pull request merged**
