### PR TITLE
Setup .gitattributes to ensure OS specific eol style

### PR DESCRIPTION
**Pull request by glensc**
Some files have somehow been committed with CRLF line endings.

This adds configuration that automatic conversion is performed depending on OS.

NOTE: When reviewing, enable ignoring whitespace changes:
- https://github.com/Taxel/PlexTraktSync/pull/115/files?w=1

### CODE REVIEW

**Comment by glensc** [comment]
Might need to rebase, depending on which gets merged first:
- https://github.com/Taxel/PlexTraktSync/pull/116

**Comment by glensc** [comment]
@twolaw, @Taxel can you approve and/or merge this and other PR's I've submitted?

What's the flow anyway, should I ping every time PR is complete? or you subscribe anyway to all activity?

**Comment by glensc** [comment]
> [@twolaw wrote](https://github.com/Taxel/PlexTraktSync/pull/114#issuecomment-791279537):
>
> Hi glensc, I approve only PR I am sure to fully understand the benefits.
>
> Taxel remains the leader here.
> Just like you, I don't understand why many things are started and not finished (files structure reorganised, trakt requests limit, new plex agent, docker,...)

The benefit here is that mixing your platform newlines, creates unreadable diffs as the whole fille will be modifed, even if you did not intend to make such newline changes because your editor did.

After this PR, all platforms commit and checkout their native EOL style.

**Comment by glensc** [comment]
@twolaw my version of code re-structure:
- https://github.com/Taxel/PlexTraktSync/pull/116

depends on the current PR:
- https://github.com/Taxel/PlexTraktSync/pull/115

otherwise, there's exactly that whole file diffs show as removed+add, instead of file move.

**Review by twolaw — APPROVED** [review]

**Pull request merged**
