### PR TITLE
Bump typed-ast to 1.4.2

### LINKED ISSUE #108: Installing requirements.txt fails on Python 3.9
I'm using Python 3.9 on the Mac that I'm running this script (it's running macOS 10.15.7). Both pip and pip3 are pointed to `/Library/Frameworks/Python.framework/Versions/Current/bin/python3`, which at the moment is `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3`.

Running `pip3 install -r requirements.txt` failed at the part where it's trying to install typed_ast, version 1.4.0. I found [this GitHub issue](https://github.com/python/typed_ast/issues/126) where it appears this was resolved in version 1.4.2. I modified requirements.txt to include `typed-ast==1.4.2` instead, and was able to install successfully. The Trakt/Plex sync works OK now.

I don't know the greater implications of this, so I figured I'd submit an issue before a pull request. If you'd like a pull request for this, just let me know.

### PR DESCRIPTION
**Pull request by flammable**
This fixes installation errors with Python 3.9.

Closes #108

### CODE REVIEW

**Review by glensc — APPROVED** [review]

**Comment by glensc** [comment]
@flammable please keep Pipfile* in sync with requirements.txt

**Comment by glensc** [comment]
@flammable also, you should never make pull request from your master branch.

**Comment by glensc** [comment]
build log ok:

```
Collecting typed-ast==1.4.2
  Using cached typed_ast-1.4.2-cp39-cp39-macosx_10_9_x86_64.whl (225 kB)
Requirement already satisfied: six==1.12.0 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (1.12.0)
Installing collected packages: typed-ast, PlexAPI
  Attempting uninstall: PlexAPI
    Found existing installation: PlexAPI 3.2.0
    Uninstalling PlexAPI-3.2.0:
      Successfully uninstalled PlexAPI-3.2.0
Successfully installed PlexAPI-4.3.1 typed-ast-1.4.2
```

**Comment by flammable** [comment]
> @flammable please keep Pipfile* in sync with requirements.txt

Oh, I didn't notice that! I'll add that as an additional change.

> @flammable also, you should never make pull request from your master branch.

Sorry, I'm embarrassed to admit that I haven't figured out git branching yet. :(

**Comment by flammable** [comment]
How's that look? 😄

**Comment by glensc** [comment]
@flammable I deliberately said Pipfile*, meaning it'll expand to two files, so no go yet.

**Comment by flammable** [comment]
Ah, I see. I don't know how to use Pipfiles. Do you want to handle this part?

**Comment by glensc** [comment]
here's how can add dependency conditionally:

```diff
--- a/requirements.txt
+++ b/requirements.txt
@@ -15,7 +15,12 @@ requests-oauthlib==1.2.0
+
+# the typed-ast is not needed on 3.9:
+# - https://github.com/Taxel/PlexTraktSync/issues/108
+# so this dependency is for older versions:
+# - https://stackoverflow.com/a/35614580/2314626
+typed-ast==1.4.0; python_version < '3.9'
```

but we'll drop the dependency instead, seems it's bogus.

see discussion at;
- https://github.com/Taxel/PlexTraktSync/issues/108

**Pull request closed without merging**
