### PR TITLE
Feature: Add watch progress syncing option

### PR DESCRIPTION
**Pull request by glensc**
Add syncing watch progress:
- https://trakt.tv/users/me/progress
- https://trakt.docs.apiary.io/#reference/sync/playback/get-playback-progress

Feature request:
- https://github.com/Taxel/PlexTraktSync/discussions/1885

Features:
- [x] sync from trakt to plex
- [ ] sync from plex to trakt
- [ ] handle priorities: plex vs trakt or trakt vs plex

NOTE: Use tppm to manage entries at trakt.tv side, i.e. removing 0% items (not sure where same functionality is on trakt.tv site):
- https://sharkykh.github.io/tppm/

Requires:
- [x] https://github.com/glensc/python-pytrakt/pull/48
  - https://github.com/Taxel/PlexTraktSync/pull/1891

### CODE REVIEW

**Comment by glensc** [comment]
trakt somewhy also has 0% entries, but these can be removed using this tool:
- https://sharkykh.github.io/tppm/

not sure where same functionality is on trakt.tv site

**Comment by glensc** [comment]
Not sure what to do with editions:

```
WARNING  Kuldrannake (2006): Skip progress, setting to 0 will not work                                                                                 
WARNING  Kuldrannake (Xtra muusika filmist) (2006): Skip progress, setting to 0 will not work     
```

should the progress be updated only for main edition? the extras length is probably way off compared to the original movie

**Comment by thierrybla** [comment]
Is it also possible to sync plex to trakt? I like this feature but it only goes one way, is there a reason it's not both ways?

**Comment by glensc** [comment]
open discussion thread or create a feature request. pull requests are not place to discuss things outside their scope

**Pull request merged**
