### PR TITLE
Updated Pull Request for Support for Plex Movie Scanner.

### PR DESCRIPTION
**Pull request by wampa1**
I wrote a fallback matcher but ... as I'm not a contributor (and work mostly in non open source repositories), I'm not 100% sure I know how to submit a pull request for it. Happy to contribute though if you like.

I'm also not a Python guy so ... it could use someone else's eyes on it.

I spent my whole day looking for an up to date app to sync the watched status of my Plex library (I reorganized it and everything was "unwatched" again). This was definitely the most promising and with my small update, it did work for my large library.

Fixes: https://github.com/Taxel/PlexTraktSync/issues/56

### CODE REVIEW

**Comment by glensc** [comment]
since you created a new PR, close the previous one ("close pull request" button at the bottom)

**Comment by glensc** [comment]
there's no point to have two commits, especially as you lost any authorship information. squash to one commit and force push can help to resolve this.

**Comment by wampa1** [comment]
> there's no point to have two commits, especially as you lost any authorship information. squash to one commit and force push can help to resolve this.

I'm failing you a bit here, very sorry. I might be out of my depth a bit on that ... I haven't done it before and would hate to cause more issues that I help solve.

If my quick google search is close to right ... do I:

git rebase -i HEAD~2
git push --force

Which I did try ... but it didn't seem to change anything.

**Comment by wampa1** [comment]
OK, I figured it out.  Thanks for your patience.

**Comment by glensc** [comment]
Edited PR body (that you replaced the previous PR is not relevant in PR context), and added a link to issue at hand.

**Review by glensc — APPROVED** [review]

**Comment by glensc** [comment]
Not sure which one is better/accurate/etc, but there's similar PR with content:
- https://github.com/Taxel/PlexTraktSync/pull/87

**Comment by glensc** [comment]
@wampa1 can you instead test the other PR works fine for you:
- https://github.com/Taxel/PlexTraktSync/pull/83#issuecomment-766615141

**Comment by wampa1** [comment]
I'll check it out tonight.  Thankful that you think of me!

**Comment by glensc** [comment]
@wampa1 don't forget to re-install python dependencies, they have been updated but I don't think there's a mechanism in place to check that they are up to date.

**Pull request closed without merging**
