### PR TITLE
Use rich library

### PR DESCRIPTION
**Pull request by glensc**
The `rich` library allows formatting of links, tables, progress bar, and more colors.

[asciicast](https://asciinema.org/a/I2YbKRkZh1v95RrMIPNwtmQu8)

Originally found the project due to interest in creating HTML links.

refs;
- https://www.willmcgugan.com/blog/tech/post/real-working-hyperlinks-in-the-terminal-with-rich/
- https://github.com/willmcgugan/rich
- https://rich.readthedocs.io

### CODE REVIEW

**Comment by glensc** [comment]
Maybe it's too much bloat, but the multiple progress bars is a really interesting feature, and I definitely would not implement that on my own from scratch.

**Comment by glensc** [comment]
rich has colorama as dependency and seems colorama has the hyperlink support:
- https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#gistcomment-2129096
  - https://github.com/tartley/colorama/issues/134

**Comment by glensc** [comment]
Escape code for just links:
- https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#gistcomment-3632194

```
alias url=$'printf \'\e]8;;%s\e\\%s\e]8;;\e\\\n\''
url 'http://example.com' 'This is a link'
```

**Comment by glensc** [comment]
The new UI can be seen with:

```
python3 tests/test_rich.py
```

syncs movies/shows, no list related code present

**Comment by Taxel** [comment]
@glensc if you just need this for the multiple progress bars: Have you tried [`tqdm`](https://github.com/tqdm/tqdm)? With the `position` parameter you can use multiple progress bars. It does not look as cool as the `rich` progress bar but is very easy to use.

**Comment by glensc** [comment]
@Taxel `tqdm`, I've only very briefly looked.

I was looking for something for hyperlinks, so items print to the screen could open in Plex Web or Trakt Web.

so I found rich, rich seems to solve some other problems as well. I also like its progress log. it can print messages and not corrupt the progress bar.

**Pull request closed without merging**
