### PR TITLE
Use incremental backoff for other exceptions than RateLimitException

### PR DESCRIPTION
**Pull request by glensc**
Closes https://github.com/Taxel/PlexTraktSync/issues/279

### CODE REVIEW

**Comment by glensc** [comment]
@BEisem can you give this a try? and report back. I'm interested to see that the retry is incremental.

**Comment by BEisem** [comment]
The sync takes about an hour and a half and it usually doesn't fail until near the end, it also doesn't happen all the time ... I'll start running it and report back.

**Comment by BEisem** [comment]
I did a movie sync and it crashed again near the end, with only 15 minutes left... see traceback attached.

[Timeout Error 2.txt](https://github.com/Taxel/PlexTraktSync/files/6338855/Timeout.Error.2.txt)

**Comment by glensc** [comment]
@BEisem Ok, now your plex is timing out. adding catch there too. and ignore such items.

altho I'm not sure if it's right to continue on such errors. perhaps the script abort is most appropriate action.

as for example, the Watchlists functionality may need that all items be scanned, otherwise they get repoved from Watchlist. just a speculation, I don't know how Watchlists work.

**Comment by BEisem** [comment]
Ok, this works... I was finally able to do a complete Movie sync. Also, I'm glad that the log shows the offending movie that was causing the problem, so I'm able to go in and fix it. It turned out that it didn't have metadata. I'm not sure why it didn't fall back to local, but in any event, this fixes my issue.

```
Processing Movies  [###---------------------------------]  1012/11127  01:13:39WARNING: Skipping <imdb:tt1704292:<Movie:378899:Battlestar-Galactica>>: Not found on Trakt
Processing Movies  [###############---------------------]  4653/11127  00:42:25WARNING: Skipping <imdb:tt0329200:<Movie:114123:Home-Alone-4:-Taking>>: Not found on Trakt
Processing Movies  [####################----------------]  6251/11127  00:32:00WARNING: Skipping <imdb:tt12403312:<Movie:268527:Lucy-Worsley's-Royal>>: Not found on Trakt
Processing Movies  [####################----------------]  6277/11127  00:31:50WARNING: Skipping <tmdb:709918:<Movie:50447:Mad-Max:-Fury-Road-(>>: Not found on Trakt
Processing Movies  [#####################---------------]  6618/11127  00:29:31WARNING: Skipping <imdb:tt6916334:<Movie:320656:The-Midas-Touch>>: Not found on Trakt
Processing Movies  [##############################------]  9479/11127  00:10:36WARNING: Skipping <imdb:tt5332042:<Movie:363850:Steve-Miller-Band:-L>>: Not found on Trakt
Processing Movies  [##################################--]  10567/11127  00:03:36WARNING: Skipping <imdb:tt13968482:<Movie:136228:Walking-with-the-Tal>>: Not found on Trakt
Processing Movies  [###################################-]  11024/11127  00:00:39WARNING: Internal Server Error for <function TraktApi.search_by_id at 0x10932c620>, retrying after 1 seconds (try: 1/5)
WARNING: Internal Server Error for <function TraktApi.search_by_id at 0x10932c620>, retrying after 2 seconds (try: 2/5)
WARNING: Internal Server Error for <function TraktApi.search_by_id at 0x10932c620>, retrying after 3 seconds (try: 3/5)
WARNING: Internal Server Error for <function TraktApi.search_by_id at 0x10932c620>, retrying after 4 seconds (try: 4/5)
WARNING: Internal Server Error for <function TraktApi.search_by_id at 0x10932c620>, retrying after 5 seconds (try: 5/5)
WARNING: Skipping <tvdb:158175:<Movie:379330:The-Year-Earth-Chang>>: Trakt errors: Internal Server Error
Processing Movies  [####################################]  11127/11127          
INFO: Processing Movies in 72 min 25.2 seconds
Processing Stand-Up Comedy  [##############----------------------]  130/323  00:01:02WARNING: Skipping <imdb:tt2243073:<Movie:365451:Hannah-Gadsby:-Kiss->>: Not found on Trakt
Processing Stand-Up Comedy  [#########################-----------]  229/323  00:00:31WARNING: Skipping <imdb:tt6140294:<Movie:365744:The-Nasty-Show-Hoste>>: Not found on Trakt
Processing Stand-Up Comedy  [####################################]  323/323          
INFO: Processing Stand-Up Comedy in 1 min 43.7 seconds
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 74 min 17.5 seconds
```

**Pull request merged**
