### PR TITLE
Use InquirerPy for user input

### PR DESCRIPTION
**Pull request by sirloinofbeef**
Simplified user input using InquirerPy:
- Server selection _(selectable list)_
image

- Managed user Y/N _(made redundant by below)_
- Managed user selection _(selectable list, including default main username)_
image

### CODE REVIEW

**Comment by glensc** [comment]
I don't see the point in adding another dependency.

the password wasn't shown already with the current implementation.

**Comment by sirloinofbeef** [comment]
Imho having * appear makes input easier / more intuitive. The main bonus though comes with the selection input for servers / users. Makes it impossible for users to enter typos or incorrect data. The managed user Y/N and selection inputs are also streamlined into a single input.

If this is not a direction wanted for the script though, that's fine, and / or I can look into coding something which doesn't require the dependancy.

**Comment by glensc** [comment]
`having * appear` only for windows users, unix users know that password input never shows anything. and you should add screenshots

**Comment by glensc** [comment]
We already have `rich` library in dependencies:
- https://github.com/willmcgugan/rich

**Comment by sirloinofbeef** [comment]
> We already have `rich` library in dependencies:
> 
> * https://github.com/willmcgugan/rich

Afaik `rich` is for RTF and doesn't offer the selection input which this change is making.

**Comment by glensc** [comment]
a4d0bbd: you misunderstood me, it's a mindset of windows users that password must be shown as stars. other users consider that that's leaking password info if you show how long is your password while you're typing and someone peeks over your shoulders. I never said you should make such changewindows only. what I said, that rather using yet another framework as dependency, use existing ones. we have click, we have rich already as deps.

it's my opinion (other maintainers might think otherwise). also, I won't support any windows specific code at all. ever. python is platform-independent and should stay that way here.

**Comment by glensc** [comment]
Server selection: you lost information of server details that were printed before

**Comment by sirloinofbeef** [comment]
> Screenshots should go to PR body
Fixed

> Server selection: you lost information of server details that were printed before
No, that information is still there. The selectable list appears directly after it as per the current server selection input.

> that's leaking password info
Completely understand. The idea of the password * is to make things more user friendly for a susbset of users. (Windows users). If this presents too much of a concern then I'm happy to remove it, particularly if it distracts from the main purpose of this push, selectable server / user input options rather than typed (which are more susceptible to to user error e.g. typos). I only tacked on the password input alteration as the dependency happened to support it on top of the selectable input options.

> I won't support any windows specific code
That's fair.

**Comment by glensc** [comment]
1. please remove platform specific code. use same style for all platforms
2. change "main user" to show actual login of main account. maybe add dash separator between it and managed users?
3. your screenshot shows only server names, doesn't show server IP, URL, last seen, server version

```
- ONEPLUS A5000: [Last seen: 2021-09-27 21:54:39, Server: Plex for Android (Mobile)/8.23.1.28053 on ONEPLUS A5000: Android/10]
    http://192.168.0.30:32500
- Vulpes: [Last seen: 2021-09-28 08:26:17, Server: Plex Media Server/1.22.3.4392-d7c624def on Docker Container (LinuxServer.io): Linux/4.14.134-boot2docker]
    https://192-168-0-xxx.plex.direct:32400
    https://192-168-0-xxx.plex.direct:32400
```

**Comment by glensc** [comment]
default password via commandline/env is lost: `default=password`

**Comment by sirloinofbeef** [comment]
> 1. please remove platform specific code. use same style for all platforms

Done

> 2. change "main user" to show actual login of main account. maybe add dash separator between it and managed users?

I'll lookup how to do this and implement.

> 3. your screenshot shows only server names, doesn't show server IP, URL, last seen, server version

Screenshot updated to show positioning in flow.

**Comment by sirloinofbeef** [comment]
> default password via commandline/env is lost: `default=password`

Double check and it IS there as per the original code.

**Comment by glensc** [comment]
> > default password via commandline/env is lost: `default=password`
> 
> Double checked and it IS there as per the original code.

yes, it's back once you removed platform-specific code.

**Pull request merged**
