### PR TITLE
Move code to plex_trakt_sync module

### PR DESCRIPTION
**Pull request by glensc**
This adds some structure to the project, following documentation:
- https://docs.python-guide.org/writing/structure/

# details
- Moved code to `plex_trakt_sync`
- Add `path` module dealing with locations of the files
- Kept entrypoints (as wrappers):
  -  `clear_trakt_collections.py`
  -  `get_env_data.py`
  -  `main.py`

This is backward compatible change (should not change anything to users who update with git pull). Tested with local sync which completed OK.

### CODE REVIEW

**Comment by glensc** [comment]
Might need to rebase, depending on which gets merged first:
- https://github.com/Taxel/PlexTraktSync/pull/115

**Comment by glensc** [comment]
@twolaw rebased after https://github.com/Taxel/PlexTraktSync/pull/115 merge.

**Comment by glensc** [comment]
> Merging is blocked
>
> Merging can be performed automatically with 1 approving review.

@Taxel can you remove that restriction?

**Comment by twolaw** [comment]
What about [this sctructure](https://github.com/Taxel/PlexTraktSync/tree/docker) where we can find a config folder ?

**Comment by glensc** [comment]
I would drop the config.json in the repository completely, it's currently not even in .gitignore.

The "src" folder does not match the Python coding style.

My vision is that the defaults will be inlined in code, and if the config file is wanted, it's generated on first use or something. and most of the config values can be overridden via env and/or command line. the config should be in XDG_CONFIG_HOME, overridable with --config or some env. env override is perfect for Docker usage.

Once these are done, can even distribute the project as pip package, and then can install via pip and is execute from PATH. for example this project:
- console.cloud.google.com/bigquery

**Comment by glensc** [comment]
> What about [this sctructure](https://github.com/Taxel/PlexTraktSync/tree/docker?rgh-link-date=2021-03-13T10%3A24%3A06Z) where we can find a config folder ?

But answer to your question, this PR does not move config location, it stays in the project root. you can see what is moved summary in PR body.

**Comment by glensc** [comment]
@twolaw can you approve this, please? I want to make changes, but not to old codebase, and this is the blocker preventing me to move forward.

**Comment by twolaw** [comment]
> 
> 
> I would drop the config.json in the repository completely, it's currently not even in .gitignore.
> 
> My vision is that the defaults will be inlined in code, and if the config file is wanted, it's generated on first use or something. and most of the config values can be overridden via env and/or command line. the config should be in XDG_CONFIG_HOME, overridable with --config or some env. env override is perfect for Docker usage.

A sample config file copied by script at first run is good. So that users can read it when they discover the repo and be sure it fits their needs.

**Review by twolaw — APPROVED** [review]

**Comment by glensc** [comment]
Rebase seems to be without errors:

```
Completed full sync in 2 min 57.8 seconds
```

**Comment by twolaw** [comment]
We can discuss about `get_env_data.py` being an entrypoint.

**Comment by glensc** [comment]
> We can discuss about `get_env_data.py` being an entrypoint.

I'm assuming you want to drop it. Go ahead, My concern here was that I don't know how whether users executed it directly before. So I added the entrypoint to keep this PR fully backward compatible.

**Comment by glensc** [comment]
@twolaw there are other weird entrypoints:

```
clear_trakt_collections.py
get_env_data.py
```

but I'd address this after https://github.com/Taxel/PlexTraktSync/pull/122 merge.

as then could have subcommand, and or just via command-line option invoke some other code.

**Pull request merged**
