### PR TITLE
Merge up 0.6.x to master

### PR DESCRIPTION
**Pull request by glensc**
This creates a merge up so that master can have development done for 0.6.x development.

This PR includes following `0.6.x` releases:

- `0.6.44` #229 Move sleeping messages to debug log level
- `0.6.43` #223 Add error catching of NotFound plex items 
- `0.6.42` #222 Fix TV episodes matching for new TV agent
- `0.6.41` #221 Fix trakt username display on startup
- `0.6.40` #206 Move TV shows sync logic to sync command
- `0.6.39` #201 Remove unneeded POST delay from trakt.me method
- `0.6.38` #204 Add method to clear cache and reload item
- `0.6.37` #202 Add replace of thetvdb to tvdb
- `0.6.36` #205 Update find_movie to find also shows
- `0.6.35` #203 Improve error handling for find_movie method
- `0.6.34` #179 Add/update copyright notices
- `0.6.33` #197 Refactor Scrobbing to use more cleaner APIs
- `0.6.32` #198 Update last_time when rate limiting POST requests
- `0.6.31` #199 Add PLEX_PLATFORM constant
- `0.6.30` #196 Fix py 3.7 compatibility
- `0.6.29` #193 Include logger name to log messages
- `0.6.28` #194 Cleanup: Move movies sync logic to sync command
- `0.6.27` #192 Add scrobbling support to watch command
- `0.6.26` #191 Add --sync={all|tv|movies} option
- `0.6.25` #188 Use our Plex/Trakt API classes to sync collections
- `0.6.24` #148 Add watch subcommand to print play events from PMS
- `0.6.23` #186 Sync watched using our Plex/Trakt API classes
- `0.6.22` #184 Fix portabilty of plex_trakt_sync.sh
- `0.6.21` #185 Move clear_trakt_collections logic to commands/clear_collections
- `0.6.20` #181 Move plex_server logic to separate module
- `0.6.19` #180 Refactor: Sync ratings using Plex/Trakt API classes
- `0.6.18` #183 Rewrite nocache as function to support decorators on class method arguments
- `0.6.17` #177 Add rate limit delay support
- `0.6.16` #178 Add find_movie trakt api method
- `0.6.15` #176 Add rate_limit decorator
- `0.6.14` #175 Move decorators to own namespace
- `0.6.13` #174 Refactor Movies processing
- `0.6.12` #173 Add movies and shows accessors to PlexApi
- `0.6.11` #168 Identify as PlexTraktSync for X-Plex-Platform header
- `0.6.10` #166 Add TraktApi class dealing with caching/fetching trakt api methods
- `0.6.9` #167 Update to use config save() method in get_plex_server
- `0.6.8` #165 Use memoize from functools
- `0.6.7` #164 Add measure_time helper to log block timing
- `0.6.6` #141 Refactor: Add requests_cache module wrapper
- `0.6.5` #163 Add clear_trakt_collections as subcommand
- `0.6.4` #151 Add dockerfile to build the app
- `0.6.3` #149 Update logging configuration to add stdout logger
- `0.6.2` #122 Feature: Use click package for command line parsing
- `0.6.1` #142 Feature: Add PlexApi class for dealing with Plex Api fetching and caching
- `0.6.0` #159 Create CONTRIBUTING.md file

### CODE REVIEW

**Comment by glensc** [comment]
I've started to merge new stuff to the 0.7.x branch:
- https://github.com/Taxel/PlexTraktSync/pull/211

so there be time to review this PR.

**Comment by twolaw** [comment]
Sorry I will not review and approve this huge PR because I'm not skilled enough and I think such a big change should be approved by @Taxel.

**Comment by glensc** [comment]
I don't expect you to do a code review, if it works functionally, it should be fine.

**Comment by wandabastyle** [comment]
So you asked for testing of the main branch to ultimatily merge the code into master, right?

Here is what I get so far (all using the new metadata agents inside plex for tv & movies):

Syncing of the movie llibrary using `./plex_trakt_sync.sh sync --sync=movies` is working, at least as far as I know.

Syncing of the tv library using `./plex_trakt_sync.sh sync --sync=tv` leads in my case to an error.
Keep in mind that I am using the beta agent of plex.

Attached you will find the [error.log](https://github.com/Taxel/PlexTraktSync/files/6290683/error.log) and the last lines of 
[last_update.log](https://github.com/Taxel/PlexTraktSync/files/6290691/last_update.log).

Seems to be the same error mentioned in #220.

**Review by twolaw — APPROVED** [review]

**Comment by glensc** [comment]
Merging this to `master`:
- https://github.com/Taxel/PlexTraktSync/issues/162#issuecomment-821789691

thank you all for testing!

**Pull request merged**
