### PR TITLE
Add support fetching episodes by episode guid

### PR DESCRIPTION
**Pull request by glensc**
Fetch each episode, to overcome episode not found errors:
- https://github.com/Taxel/PlexTraktSync/discussions/208#discussioncomment-611321

This also adds a new warning when episode belongs to a different show:

```
WARNING: EPISODE_NAME does not belong to same Show SHOW_NAME: Matches SHOW_NAME
```

### CODE REVIEW

**Comment by glensc** [comment]
@BEisem can you confirm this PR:
1. doesn't break things more than before?
2. fix some of the issues from https://github.com/Taxel/PlexTraktSync/discussions/208?

**Comment by BEisem** [comment]
Something is causing the sync to go very slowly in this version.

It took about 2-3 minutes to get past the line "3/418" and now it's been sitting at the last line "4/18" for at least 5 minutes. It isn't crashing, but it's doing something that is taking a very long time. Previous versions of the script didn't take this long.

Also, it looks like there is a line break missing before "WARNING" and "ERROR."

```
bink@Homey-McPlexFace plex-trakt-sync-ep-lookup-quick % ./plex_trakt_sync.sh sync --sync=tv
INFO: Syncing with Plex BlaEis and Trakt binkatl
INFO: Syncing TV=True, Movies=False
INFO: Loaded Trakt lists in 3.7 seconds
INFO: Server version 1.22.2.4282-a97b03fad updated at: 2021-04-15 13:30:40
INFO: Recently added: [<Movie:123435:Billy-Connolly:-Live>, <Season:198111:Wahl-Street-s1>, <Season:198096:The-$100,000-Pyramid-s1>, <Season:198082:The-$100,000-Pyramid-s2>, <Season:198067:The-$100,000-Pyramid-s3>]
ERROR: Skipping <local:198101:<Episode:198101:The-$100,000-Pyramid-s01e05>>: Provider local not supported
ERROR: Skipping <local:198102:<Episode:198102:The-$100,000-Pyramid-s01e06>>: Provider local not supported
ERROR: Skipping <local:198103:<Episode:198103:The-$100,000-Pyramid-s01e07>>: Provider local not supported
ERROR: Skipping <local:198104:<Episode:198104:The-$100,000-Pyramid-s01e08>>: Provider local not supported
ERROR: Skipping <local:198105:<Episode:198105:The-$100,000-Pyramid-s01e09>>: Provider local not supported
ERROR: Skipping <local:198106:<Episode:198106:The-$100,000-Pyramid-s01e10>>: Provider local not supported
ERROR: Skipping <local:198064:<Episode:198064:The-$100,000-Pyramid-s04e11>>: Provider local not supported
ERROR: Skipping <local:198065:<Episode:198065:The-$100,000-Pyramid-s04e12>>: Provider local not supported
ERROR: Skipping <local:198066:<Episode:198066:The-$100,000-Pyramid-s04e13>>: Provider local not supported
Processing Reality / Talk / Documentary TV  [------------------------------------]  1/418  00:51:21WARNING: Skipping <imdb:tt12169564:<Show:82398:100-Day-Dream-Home>>: Not found on Trakt
Processing Reality / Talk / Documentary TV  [------------------------------------]  3/418  00:39:20ERROR: Skipping <local:82486:<Episode:82486:16-and-Pregnant-s03e14>>: Provider local not supported
ERROR: Skipping <local:82514:<Episode:82514:16-and-Pregnant-s05e15>>: Provider local not supported
ERROR: Skipping <local:82522:<Episode:82522:16-and-Pregnant-s06e07>>: Provider local not supported
ERROR: Skipping <local:82523:<Episode:82523:16-and-Pregnant-s06e08>>: Provider local not supported
ERROR: Skipping <local:82524:<Episode:82524:16-and-Pregnant-s06e09>>: Provider local not supported
ERROR: Skipping <local:123163:<Episode:123163:16-and-Pregnant-s06e10>>: Provider local not supported
ERROR: Skipping <local:197590:<Episode:197590:16-and-Pregnant-s06e11>>: Provider local not supported
Processing Reality / Talk / Documentary TV  [------------------------------------]  4/418  02:14:33
```

**Comment by glensc** [comment]
enable debug logs in the config, I'm sure it's doing fetch of each episode. so this is expected over accuracy.

the progress bar and warning/error messages do not go well. it's documented in click documentation. there's no solution offered.

**Comment by BEisem** [comment]
I see. This is unfortunate, since this new method (searching by episode) is much slower than the other method. At this rate, it's going to take 4-5 hours to scan my library.

**Comment by glensc** [comment]
progressbar estimated 02:14:33 :)

however, the incremental run should go better?

**Comment by BEisem** [comment]
```
Processing Reality / Talk / Documentary TV  [------------------------------------]  10/418  05:43:59WARNING: Skipping <imdb:tt13780778:<Show:83113:90-Day-Bares-All>>: Not found on Trakt
Processing Reality / Talk / Documentary TV  [------------------------------------]  11/418  05:43:08
```

It's up to 5:43:08 at this point ... and that's just for my Reality TV library, my regular TV library is much larger. And this technically isn't an initial scan, since I copied `trakt_cache.sqlite` from my working version. Unless it's downloading all new information?

I'll let it keep running, but right now it's feeling like this is not going to work in its current form...

**Comment by glensc** [comment]
yes, the requests it makes are not cached. you can enable debug log to see what requests it makes. you can interrupt the process and see that the already cached shows (11) will go fast.

**Comment by glensc** [comment]
The api method currently used:
- https://trakt.docs.apiary.io/#reference/search/id-lookup/get-id-lookup-results

does not support fetching multiple items, i.e filter by imdb:123, imdb:456

**Comment by BEisem** [comment]
Ok great, yes the cached shows did go much faster. Still, this initial scan is likely going to take all day. So far so good though. I'll let it keep running, then when this version is merged, I should be able to copy my trakt_cache.sqlite over...

Speaking of merging, other than the scan, was there anything else you wanted me to test with this version? It seems to be working well (other than the initial speed, which I guess can't be helped)

**Comment by glensc** [comment]
The previous code (and legacy scanner sill does), uses this api method:
- https://trakt.docs.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show

which makes one huge request per show, rather than many small requests for each episode.

**Comment by glensc** [comment]
I don't know what to do with this PR if the initial scan is that terrible. This was created to solve some problem from https://github.com/Taxel/PlexTraktSync/discussions/208.

maybe this should be changed to "verify" command, to check plex library for inconsistencies, but regular update would still use the single query per show.

**Comment by glensc** [comment]
> Speaking of merging, other than the scan, was there anything else you wanted me to test with this version? It seems to be working well (other than the initial speed, which I guess can't be helped)

This PR is solving the problem that it links in PR body. Is that problem solved with this branch?

**Comment by BEisem** [comment]
I don't know yet, the scan hasn't gotten down to the show that was causing the initial problem ... it will take several hours to get to that point. But you're right, at this pace, it doesn't really seem useful to be able to run this as an initial scan.

**Comment by BEisem** [comment]
> I don't know what to do with this PR if the initial scan is that terrible. This was created to solve some problem from #208.
> 
> maybe this should be changed to "verify" command, to check plex library for inconsistencies, but regular update would still use the single query per show.
> 
> or use the "quick" mode by default, and fall back to "slow" mode when episodes not found... should draw the line somewhere.

I actually just had an idea about this.

Is it possible to issue a command only on a specific show, or specific episode? So the default could be for the quick mode, as you said. And then if the user sees an error in the log for a specific show, they could run the "deep scan" just for that show. This would be a lot more efficient, and probably just as beneficial, since only problematic shows would have to go through the slower scan.

So maybe `./plex_trakt_sync.sh deepsync [ID]` or something along those lines. The user could find the ID from the initial scan, and run a dep scan only on those items.

**Comment by glensc** [comment]
but then the user keeps running the 'deepsync'? plextraktsync can't fix problems with plex library. the point of the verify mode I suggested, was that user is shown errors of their library, so they can correct these.

on the other hand, we can already right now say, "Not found on trakt" could mean problem with plex library.

**Comment by BEisem** [comment]
Ok, I understand. So maybe it's not necessary.

But you made a comment earlier, "Fix your library" ... while I understand that's what needs to happen, I'm not quite sure how to do that in some instances. I've been going through and fixing what I can. But the fact is, sometimes certain things just aren't lining up correctly.

For example, from my logs:

`WARNING: Skipping <imdb:tt13780778:<Show:325982:90-Day-Bares-All>>: Not found on Trakt`

This show is not being found on Trakt. But here it is:
https://trakt.tv/shows/90-day-bares-all/seasons/all

On the Trakt site, the IMDB link is broken, instead of showing the correct IMDB ID, it shows https://www.imdb.com/find?q=90+Day+Bares+All&s=tt

This is outside of my control, I suppose? Or is there a way I can fix this?

**Comment by glensc** [comment]
This PR was born of a concrete example:

```
2021-04-14 18:35:52,319 WARNING[PlexTraktSync]:Skipping <imdb:tt14116976:<Episode:224716:Whose-Line-Is-It-Any-s17e06>>: Not found on Trakt
2021-04-14 18:35:52,359 WARNING[PlexTraktSync]:Skipping <imdb:tt14136386:<Episode:224717:Whose-Line-Is-It-Any-s17e07>>: Not found on Trakt
2021-04-14 18:35:52,399 WARNING[PlexTraktSync]:Skipping <tvdb:8202026:<Episode:224718:Whose-Line-Is-It-Any-s17e08>>: Not found on Trakt
2021-04-14 18:35:52,447 WARNING[PlexTraktSync]:Skipping <tvdb:8244885:<Episode:228073:Whose-Line-Is-It-Any-s17e09>>: Not found on Trakt
```

- https://github.com/Taxel/PlexTraktSync/discussions/208#discussioncomment-611321

which this PR should handle properly (better?). can you confirm that?

**Comment by glensc** [comment]
rebased against https://github.com/Taxel/PlexTraktSync/pull/247, so the `--show` option works on this branch as well.

**Comment by BEisem** [comment]
Ok this is great! I think this is going to help immensely for problematic shows.

I think you should add some sort of error if the show isn't found. It took me a few attempts of trying different versions of the show name before it worked (I forgot the question mark at the end of the name). The script just exited without saying anything ... I think a "Show not found" message would be helpful.

**Comment by BEisem** [comment]
Also, it was scanning and got part of the way through the episodes, then it just crashed with the following:

```
Traceback (most recent call last):
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/trakt_api.py", line 207, in find_by_media
    search = trakt.sync.search_by_id(media_id, id_type=pm.provider, media_type=media_type)
  File "/Library/Python/3.7/site-packages/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/Library/Python/3.7/site-packages/trakt/core.py", line 527, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/Library/Python/3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/commands/sync.py", line 240, in sync
    sync_all(movies=movies, tv=tv, show=show)
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/commands/sync.py", line 194, in sync_all
    for tm, pe, te in it:
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/commands/sync.py", line 134, in find_show_episodes
    for tm, pe, te in for_each_show_episode(pm, tm, trakt):
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/commands/sync.py", line 150, in for_each_show_episode
    te = trakt.find_episode(pe, pm)
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/trakt_api.py", line 223, in find_episode
    return self.find_by_media(pe)
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/decorators/rate_limit.py", line 45, in wrapper
    return fn(*args, **kwargs)
  File "/Users/bink/scripts/plex-trakt-sync-ep-lookup-quick/plex_trakt_sync/trakt_api.py", line 210, in find_by_media
    raise ValueError(f"Invalid id_type: '{pm.provider}', guid: '{pm.guid}', guids: '{pm.guids}': {e}") from e
ValueError: Invalid id_type: 'imdb', guid: 'imdb://tt4839322', guids: '[<Guid:imdb://tt4839322>, <Guid:tvdb://5250724>]': Expecting value: line 1 column 1 (char 0)
```

I'm going to run it again to see if it completes, but I wanted to report this first...

**Comment by BEisem** [comment]
It also might be nice to have the option of using the Show ID as well (instead of just the title). Because this can be seen in the logs, it would be easy to just copy that number and use it instead of the title.

But don't remove the option of using the title, just give both options... just my suggestion, not terribly important...

**Comment by BEisem** [comment]
One other thing ... I just ran it a second time on the same show (Whose Line Is It Anyway?) ... and it went much quicker, but it still reported "Add to Trakt Collection." Should it be reporting that again, even though it should have already added it on the last run? Is there another message it should be reporting when something is already in the colleciton?

**Comment by glensc** [comment]
```
ValueError: Invalid id_type: 'imdb', guid: 'imdb://tt4839322', guids: '[<Guid:imdb://tt4839322>, <Guid:tvdb://5250724>]': Expecting value: line 1 column 1 (char 0)
```

I think you have not installed new requirements.txt (), this reports `ValueError` as json parse error

- https://github.com/Taxel/PlexTraktSync/releases/tag/0.7.16
- https://github.com/Taxel/PlexTraktSync/pull/242

**Comment by glensc** [comment]
> I think you should add some sort of error if the show isn't found.

wishful thinking. but due to the way it's implemented, the --show option is merely a hint, at that time the option does not know if the show exists or not.

also, comment where the feature was added, nobody in their sane mind would know to look for comments related to the feature in this pull request thread!

**Comment by BEisem** [comment]
By the way, this "episode by episode" test seems to be working, but unfortunately, I can't fully test it until it is merged with 0.7. The reason is, I would need to do a full scan after doing the episode scan on a single show, to make sure the results remain in the db and it doesn't continue to throw the "Not found on Trakt" error on the full scan.

**Comment by BEisem** [comment]
I guess once this is merged, there will need to be a separate command to trigger the episode scan. Or will the `--show` command automatically trigger the deeper episode scan, while the full scan will do the faster scan?

**Comment by glensc** [comment]
The `--show` is just a shortcut to process a specific show:

If the normal loop does:
1. walk each section
2. walk each show
3. walk each episode

then with `--show` option, the code jump directly to "3.".

there's no trigger or separate command. full scan and `--show` will use the same code, and thus same HTTP cache will be filled.

using `--show` does not "fix" anything differently than a full scan does.

aside, has your full scan finished? how long the full scan runs with HTTP cache already present? do you notice a slowdown of this branch with cache present as well?

please show the scan of the `--show` that this PR was created (lookup details from PR body), from the latest release, and from this branch for me to compare.

ps: I think this PR will not be merged, I'll try to extract out other useful logic from this PR. and need to do a different approach to solve the original problem.

**Comment by BEisem** [comment]
Unfortunately, I had to cancel the full scan. It would have literally taken days to complete.

I ran a scan on the individual show using both versions. The output is quite long so I created gists for both.

0.7.19 - https://gist.github.com/BEisem/a56d014745ddab0daa9a4b8b7163c3f3
This PR - https://gist.github.com/BEisem/25278e2c131849e80722cf6458fa69db

**Comment by BEisem** [comment]
Maybe I'm not clear on what this is supposed to do or solve.

Example: There is another new series in my library called "Frank of Ireland." It has not been added to Trakt because PlexTraktSync claims it cannot find it on Trakt. Using 0.7.19, I get:

```
2021-04-16 12:11:40,968 WARNING[PlexTraktSync]:Skipping <imdb:tt11909222:<Episode:198150:Frank-of-Ireland-s01e01>>: Not found on Trakt
2021-04-16 12:11:41,017 WARNING[PlexTraktSync]:Skipping <imdb:tt11909226:<Episode:198167:Frank-of-Ireland-s01e02>>: Not found on Trakt
2021-04-16 12:11:41,034 WARNING[PlexTraktSync]:Skipping <imdb:tt11909228:<Episode:198168:Frank-of-Ireland-s01e03>>: Not found on Trakt
2021-04-16 12:11:41,050 WARNING[PlexTraktSync]:Skipping <imdb:tt11909232:<Episode:198169:Frank-of-Ireland-s01e04>>: Not found on Trakt
2021-04-16 12:11:41,066 WARNING[PlexTraktSync]:Skipping <imdb:tt11909234:<Episode:198170:Frank-of-Ireland-s01e05>>: Not found on Trakt
2021-04-16 12:11:41,084 WARNING[PlexTraktSync]:Skipping <imdb:tt11909236:<Episode:198171:Frank-of-Ireland-s01e06>>: Not found on Trakt
```

Earlier today, I ran this PR on this series, and it added it to my collection on Trakt. I can now see that it exists in my Trakt collection (on the Trakt website, go to Collection, and I see the episodes have been added).

But then, if I go back and run 0.7.19 again, it shows the same error (Not found on Trakt). So even though the episodes are now in my Trakt collection, the script still reports that it cannot find it on Trakt.

**Comment by glensc** [comment]
@BEisem here's how PlexTraktSync works:

1. find sections from plex (in other words libraries)
2. for each section go over its items
3. for the movie section process each movie
4. for tv section, find each episode of the show, process each episode

now when each movie/episode is processed, there's another loop:
1. find a matching movie or episode depending on the type
1. check if collection sync is enabled and the item needs to be added to plex or Trakt, and add if it is so
2. check if ratings need to be synced, and do things
3. check if watched need to be synced, and do things

as you can see, for things to work, PlexTraktSync needs to find Trakt item from Plex item, if it can't find it, you'll have the Not Found on Trakt error.

so that movie or episode was synced with another version of the script, does not mean anything.

**Comment by BEisem** [comment]
Ok got it, thanks for explaining the internal process, that helps me understand.

So, here's how I see it. We have one scan method (the fast method that is in 0.7.19) that works for most, but causes some episodes to error with a "Not found on Trakt" error. We have another slower scan method that finds all episodes, but is too slow to be feasible for a full scan.

Isn't there a way to add that second scan method as a separate command, and allow the user to use that scan for just a single show? So maybe the command would look something like this:

`./plex_trakt_sync.sh scan --scan=tv` -- this would use the fast scan method on the entire TV library
`./plex_trakt_sync.sh scan --show="Some TV Show"` -- this would use the fast scan method on a single TV show
`./plex_trakt_sync.sh deepscan --scan=tv` -- this would use the slow scan method on the entire TV library (too slow for my library, but might work for smaller libraries
`./plex_trakt_sync.sh deepscan --show="Some TV Show"` -- this would use the slow scan on a single TV show

This way, when the user sees the "Not found on Trakt" errors during a full scan, they could use the slower scan to make that connection, and add the information to the sqlite db.

Would this work? Or am I still missing something?

**Comment by glensc** [comment]
I plan to implement so that on "Not found on Trakt" switch to "slow" mode for that specific episode only.

**Comment by glensc** [comment]
also, this project has no state. i.e it has no database, the `trakt_cache.sqlite` you're seeing is for caching only HTTP requests.

**Comment by BEisem** [comment]
Oh right, of course, I didn't mean a database per se, but yes, the cache...

Anyway, your idea definitely sounds like the best option .... implementing the slow mode for any episodes that get the "Not found on Trakt" error ... can't wait to test that out. Thanks!

**Comment by glensc** [comment]
@BEisem you can already test that out, using this branch and `--show` option :)

it's proven to work, just need to integrate it as described above, but need to finish up some other ideas.

**Comment by glensc** [comment]
@BEisem are you sure your Frank-of-Ireland problem is not related to http cache? remove the cache and does the full sync still not find it? (i mean of course use `--show` option)

**Comment by BEisem** [comment]
Actually, it doesn't have anything to do with the cache ... using this PR, every time I run it on "Frank of Ireland" it comes back saying "Add to Trakt Collection." Even after it has already been added (as evidenced by going to the Trakt GUI and looking at my collection). If I run this PR again on the same show, it will repeat, saying "Add to Trakt Collection."

Since it has already been added, why does it repeat the same info in the log, stating that it is adding it to the collection? Shouldn't it just not report anything?

For example if I run this PR on "Everybody Loves Raymond" ... the script runs, and then exits without report, since all the episodes already exist in my Trakt collection. But when I run it on "Frank of Ireland", every time, it reports that it is adding it to the Trakt collection...

**Comment by glensc** [comment]
Yes, it does have to do something with the cache:
- https://github.com/Taxel/PlexTraktSync/discussions/208#discussioncomment-594359

that we found another way, does not dismiss that scenario. Please confirm so that the 2021 show Not Found errors do not happen with http cache removed (`trakt_cache.sqlite`).

**Comment by glensc** [comment]
Repeated "Add to Trakt Collection" is a new symptom that I have not explored. So you're saying that on this branch now that it finds the episodes, but fails to detect they are already present in Trakt, so it continues to "Add to Trakt Collection"?

**Comment by BEisem** [comment]
Yes, that is correct. I removed `trakt_cache.sqlite` and it still continues to "Add to Trakt Collection." See below:

```
bink@Homey-McPlexFace plex-trakt-sync-ep-lookup-quick % rm trakt_cache.sqlite
bink@Homey-McPlexFace plex-trakt-sync-ep-lookup-quick % ./plex_trakt_sync.sh sync --show="Frank of Ireland"       
INFO: Syncing with Plex BlaEis and Trakt binkatl
INFO: Syncing Show: Frank of Ireland
INFO: Loaded Trakt lists in 3.6 seconds
INFO: Server version 1.22.2.4282-a97b03fad updated at: 2021-04-16 14:01:05
INFO: Recently added: [<Movie:123435:Billy-Connolly:-Live>, <Movie:198518:Psycho>, <Movie:198515:Pirates-of-the-Carib>, <Movie:198499:Philomena>, <Movie:198479:Pulp-Fiction>]
INFO: Add to Trakt Collection: <imdb:tt11909222:<Episode:198150:Frank-of-Ireland-s01e01>>
INFO: Add to Trakt Collection: <imdb:tt11909226:<Episode:198167:Frank-of-Ireland-s01e02>>
INFO: Add to Trakt Collection: <imdb:tt11909228:<Episode:198168:Frank-of-Ireland-s01e03>>
INFO: Add to Trakt Collection: <imdb:tt11909232:<Episode:198169:Frank-of-Ireland-s01e04>>
INFO: Add to Trakt Collection: <imdb:tt11909234:<Episode:198170:Frank-of-Ireland-s01e05>>
INFO: Add to Trakt Collection: <imdb:tt11909236:<Episode:198171:Frank-of-Ireland-s01e06>>
INFO: Updated plex watchlist in 0.0 seconds
INFO: Updated Trakt collection: {'existing': {'episodes': 6}}
INFO: Completed full sync in 8.5 seconds
```

**Comment by glensc** [comment]
@BEisem no, wrong test.

You did not click and read the link I gave?

To test: on released version (not this branch) remove cache and is giving the Not found on Trakt error or not?

**Comment by BEisem** [comment]
On released version, it still gives the error "Not found on Trakt."

```
bink@Homey-McPlexFace PlexTraktSync % mv trakt_cache.sqlite trakt_cache_bak.sqlite 
bink@Homey-McPlexFace PlexTraktSync % ./plex_trakt_sync.sh sync --show="Frank of Ireland"
INFO: Syncing with Plex BlaEis and Trakt binkatl
INFO: Syncing Show: Frank of Ireland
INFO: Loaded Trakt lists in 3.7 seconds
INFO: Server version 1.22.2.4282-a97b03fad updated at: 2021-04-16 14:01:05
INFO: Recently added: [<Movie:123435:Billy-Connolly:-Live>, <Movie:198518:Psycho>, <Movie:198515:Pirates-of-the-Carib>, <Movie:198499:Philomena>, <Movie:198479:Pulp-Fiction>]
WARNING: Skipping <imdb:tt11909222:<Episode:198150:Frank-of-Ireland-s01e01>>: Not found on Trakt
WARNING: Skipping <imdb:tt11909226:<Episode:198167:Frank-of-Ireland-s01e02>>: Not found on Trakt
WARNING: Skipping <imdb:tt11909228:<Episode:198168:Frank-of-Ireland-s01e03>>: Not found on Trakt
WARNING: Skipping <imdb:tt11909232:<Episode:198169:Frank-of-Ireland-s01e04>>: Not found on Trakt
WARNING: Skipping <imdb:tt11909234:<Episode:198170:Frank-of-Ireland-s01e05>>: Not found on Trakt
WARNING: Skipping <imdb:tt11909236:<Episode:198171:Frank-of-Ireland-s01e06>>: Not found on Trakt
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 5.6 seconds
```

**Pull request closed without merging**
