### PR TITLE
Add config to configure trakt auto watch threshold

### PR DESCRIPTION
**Pull request by glensc**
adds logic to do pause if watch progress is below threshold:

```py
    def stop(self, progress: float):
        if progress >= self.threshold:
            self.scrobbler.stop()
        else:
            self.scrobbler.pause()
```

Closes https://github.com/Taxel/PlexTraktSync/issues/603

Needs to be merged first:
- https://github.com/Taxel/PlexTraktSync/pull/604

### CODE REVIEW

**Comment by glensc** [comment]
I wonder can it happen that `stop()` is called before a first call to `update()`?

```
>>> None > 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'NoneType' and 'int'
>>>
```

**Comment by agneevX** [comment]
I'm getting an error when attempting to run sync with an image built from this branch:

```py
❯ docker run --rm --name pts-sync \
>   --hostname pts-sync \
>   -u "1001:1001" \
>   -v /opt/appdata/plextraktsync:/app/config \
>   pts/scrobbler-progress sync
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 16, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 76, in sync
    logger.info(f"PlexTraktSync [{version()}]")
  File "/app/plextraktsync/version.py", line 19, in version
    if __version__[-1] != 'x':
IndexError: string index out of range
```

**Comment by agneevX** [comment]
With debugging enabled, `last_update.log`:

```py
❯ cat /opt/appdata/plextraktsync/last_update.log
2021-11-22 12:03:32,848 DEBUG[requests_cache.backends]:Initializing backend: None /app/config/trakt_cache
2021-11-22 12:03:32,848 DEBUG[requests_cache.backends.base]:Initializing SQLitePickleDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0xffff9d18e440>
2021-11-22 12:03:32,849 DEBUG[requests_cache.backends.sqlite]:Opening connection to /app/config/trakt_cache.sqlite:responses
2021-11-22 12:03:32,857 DEBUG[requests_cache.backends.base]:Initializing SQLiteDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0xffff9d18e440>
2021-11-22 12:03:32,858 DEBUG[requests_cache.backends.sqlite]:Opening connection to /app/config/trakt_cache.sqlite:redirects
```

**Comment by glensc** [comment]
@agneevX fixed with https://github.com/Taxel/PlexTraktSync/pull/617, but the proper way would be for you to make a separate bug report, and actually tell how you built your image, i.e make **reproducible** bug report!

**Comment by glensc** [comment]
added docs needed label -- for community to document the change

**Pull request merged**
