### PR TITLE
Sync episode last viewed date from Plex to Trakt & timezone fix

### LINKED ISSUE #19: Watched dates from episodes not correctly synced from Plex to trakt
Hi, so I've got this strange issue that episodes watch dates from Plex are not synced correctly when the script is run. Meaning, that when I watched an episode on Plex, I expect the episode on trakt to have the same watched timestamp. Instead it seems to have the timestamp from the sync.

Strangely enough, the issue doesn't arise with movies, there the timestamp sync works without issues and as expected.

### PR DESCRIPTION
**Pull request by twolaw**
#11 pull-request was sync movie last view date correction.
Here is the same for tv episode.
Fixes #19 issue.

### CODE REVIEW

**Comment by twolaw** [comment]
Correction added : for watched status sync from plex to trakt, it sends UTC time to trakt (as expected by trakt api).
Sending local time to trakt is wrong.

**Comment by glensc** [comment]
yeah, I just noticed that my trait was scrobbed 3 hours ahead of the current time (my timezone is GMT+3)

**Comment by glensc** [comment]
@twolaw could you please fix issue title to say that this fixes timezone

@Taxel could you please merge this?

**Comment by glensc** [comment]
merged this to my fork:
- https://github.com/glensc/PlexTraktSync
- https://github.com/glensc/PlexTraktSync/commit/1815c1c7272aefc57e0c30949f7c298be81f04cd

**Pull request merged**
