### PR TITLE
Reorganised readme

### PR DESCRIPTION
**Pull request by sirloinofbeef**
Reorganised readme so it is easier to follow.
- Each step is now a dot point, with alternative options (such as Pipenv) being listed with `or` to make it clear.
- New `Commands` section gathers together Sync, Unmatched & Watch into one logical space, to which further commands can be added as needed.
- Previous `Notes` footnotes have been redistributed to their logical sections for easier reference.

### CODE REVIEW

**Comment by glensc** [comment]
LGTM, @twolaw what you?

**Comment by twolaw** [comment]
In `Setup`, the creation of Trakt App must remain the first step. And then user runs the script.

**Comment by sirloinofbeef** [comment]
> In `Setup`, the creation of Trakt App must remain the first step. And then user runs the script.

Happy to move it if people feel strongly about it.

The creation of a Trakt app is explained within the script though at the appropriate point using the exact same text.
Why double up on the instruction?
It makes more sense (to me) to have it alongside the other info we have there, which is also covered in-script during setup.

**Comment by twolaw** [comment]
> The creation of a Trakt app is explained within the script though at the appropriate point using the exact same text.
> Why double up on the instruction?
> It makes more sense (to me) to have it alongside the other info we have there, which is also covered in-script during setup.

In the script, it is a reminder just in case the user forgot : `If you do not have...` . The original order is to create the App before launching the script.
Asking user to do both in parallel (run script, then stop what you're doing on it to go create an app on the web) is more complicated IMHO.

Also, like you I'm not found of [doubling](https://github.com/Taxel/PlexTraktSync/commit/9a0efc0c4b6fa561b92429e06ee8f01049e8b9ca) the instructions. I think readme file is the only correct place for it.
I think script reminder should only say `If you do not have a Trakt client ID and secret, please read instructions in readme file.`

**Comment by sirloinofbeef** [comment]
> Asking user to do both in parallel (run script, then stop what you're doing on it to go create an app on the web) is more complicated IMHO.
A compelling point well made. I'll make the change.

> I think script reminder should only say `If you do not have a Trakt client ID and secret, please read instructions in readme file.`
My preference is to keep it with the instructions, as if people have missed this step they don't have to go hunting for the info.

**Comment by twolaw** [comment]
Ok, it looks good to me 👍

**Pull request merged**
