### PR TITLE
Create and publish a Docker image

### LINKED ISSUE #411: Feature request: official docker repository
### Feature description

Having an official docker repository with the build tags ready to be used.   

### Use case

Instead of having to install python and all the requirements we could just use it in a container and run it without needing to install it. A benefit to this is that if someone is saying they are using docker with tag X it easier to troubleshoot than to guess what python version they are using and if the installation was correct. 

### Workarounds

https://hub.docker.com/r/kahooli/plextraktsync
Not up to date, also not using tags which i am no fan of.  

### Plan to implement

I could try but i am not fluent in python with what is best practices for running code in containers.
There was a Dockerfile if its ready to use would only need to configure github to push finished image to a repository, and some docs so it would be easy to understand

### PR DESCRIPTION
**Pull request by chrillep**
[Create and publish a Docker image to GHCR](https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
) 
on push to main branch and tags

`$ docker pull ghcr.io/taxel/plextraktsync:latest` pulls latest build on main branch
`$ docker pull ghcr.io/taxel/plextraktsync:$tag` pulls $tag

Fixes #411

### CODE REVIEW

**Comment by glensc** [comment]
Please update PR body in what form (example of docker image paths) the images are published and when (is git tag sufficient or must use github releases?).

Then this is good to go!

In my opinion, the documentation and docker-compose can be added once this is merged and functioning.

a word on code style: (in the future) avoid using references in commit messages. creates a mess when rebasing. references are ok in PR body.

**Comment by chrillep** [comment]
> must use github releases

currently yes. 

you can trigger on tags aswell but It just seemed more complicated for the use case. 
https://github.com/docker/build-push-action#advanced-usage
https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

**Comment by chrillep** [comment]
> example of docker image paths

ill look into what is used exactly what paths are used. I just basicly copy pasted the template and it worked =).
But yeah you probably want to be able to map some files into the container.

**Comment by glensc** [comment]
I did mean docker image urls: ghcr.io/ffff/bbbb

Mapping files to container should be in PR adding docker compose.

**Comment by glensc** [comment]
we don't use GitHub releases in this project, but git tags.

can you change it to:
- build on "main" -> publish "latest"
- build on tags -> publish $tag

**Comment by chrillep** [comment]
> * build on "main" -> publish "latest"
> * build on tags -> publish $tag

ok so as i understand it latest will follow semver if publishing tags that are earlier versions
https://github.com/docker/metadata-action#flavor-input
https://github.com/docker/metadata-action#latest-tag

as for building main branch, this will be easiest handled by using **_main_** as tag

**Comment by glensc** [comment]
What for the scheduled build? Should build on pushes to main branch (includes merges), also I'm not sure we need builds on pull requests. Let's be green to the planet and not do these.

**Comment by glensc** [comment]
I would build `main` -> `latest`, but maybe publishing the last tag as `latest` is a great idea.

neither of them guarantees any stability, any merge to `main` or git tag could introduce breakage.

and it is, in fact, still true, 0.13.x suffers cache problem if you have look at open issues :)

**Comment by chrillep** [comment]
> I would build `main` -> `latest`, but maybe publishing the last tag as `latest` is a great idea.

i think getting getting latest would benefit from getting the latest tagged commit.

This was more of "the way it works" tho :)
i guess you could check if it's building latest commit from main branch and set [latest tag](https://github.com/docker/metadata-action#latest-tag) = true

I feel a little out of my depth on the exact workings of https://github.com/docker/metadata-action :)

I see now that as i set a cron schedule it also builds "nightly" every day =)
https://github.com/chrillep/PlexTraktSync/pkgs/container/plextraktsync

as far as stability isn't [Major version zero](https://github.com/docker/metadata-action#major-version-zero unstable anyway ? :)
Not that everyone using PlexTraktSync is gonna consider that and say ooh, ok then :)

ill test checking branch name and set latest

**Comment by chrillep** [comment]
> also I'm not sure we need builds on pull requests.
apparently the trigger on tags forces u to add
if: github.event_name != 'pull_request' to skip on prs :(

**Comment by glensc** [comment]
> > also I'm not sure we need builds on pull requests.
> 
> apparently the trigger on tags forces u to add
> if: github.event_name != 'pull_request' to skip on prs :(

don't understand. why?
explain? show errors?

as I see, this should work:

```yaml
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
```

**Comment by glensc** [comment]
and i think (without deeply diving into docs), the ref, schedule and sha should be dropped too:

```diff
-            type=schedule
-            type=ref,event=branch
-            type=ref,event=pr
             type=semver,pattern={{version}}
             type=semver,pattern={{major}}.{{minor}}
             type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }}
-            type=sha
```

**Comment by chrillep** [comment]
> don't understand. why?
> explain? show errors?

a pr branch in my repo built a container.
it was a misstake on my part it had older code 🤦🏼

**Comment by glensc** [comment]
@chrillep is this ready now? looks okay to me.

**Comment by chrillep** [comment]
> @chrillep is this ready now? looks okay to me.

yep yep 😊

**Comment by glensc** [comment]
🤞🏿 let's see if main branch build triggers now!

**Comment by glensc** [comment]
it did! 🎉 

- https://github.com/Taxel/PlexTraktSync/actions/runs/1102839184

**Comment by glensc** [comment]
do you see the details of that job?

```
 {
    "tags": [
      "ghcr.io/taxel/plextraktsync:main",
      "ghcr.io/taxel/plextraktsync:latest"
    ],
```

it tags `:latest` for `main` build. but I thnk we agreed `:latest` would be updated only on tags...

**Comment by glensc** [comment]
For the future documentation PR, the published docker images can be seen from here:
- https://github.com/Taxel/PlexTraktSync/pkgs/container/plextraktsync

**Comment by glensc** [comment]
@chrillep will you deal with this?
- https://github.com/Taxel/PlexTraktSync/pull/413#issuecomment-893778111

**Comment by glensc** [comment]
here's the pipeline for 0.13.11 tag build:
- https://github.com/Taxel/PlexTraktSync/actions/runs/1105967854

this created docker tags for tags as expected:
```
Docker tags
  ghcr.io/taxel/plextraktsync:0.13.11
  ghcr.io/taxel/plextraktsync:0.13
```

but we agreed that tags build will also build ":latest" what it did not here.

**Comment by chrillep** [comment]
oh I thought we agreed on the reversed.

should every main build get latest or only tags?

**Comment by glensc** [comment]
@chrillep seems you're not reading the comments:
- https://github.com/Taxel/PlexTraktSync/pull/413#issuecomment-893778111
- https://github.com/Taxel/PlexTraktSync/pull/413#issuecomment-894257513
- https://github.com/Taxel/PlexTraktSync/pull/413#issuecomment-894426561

and yes, you proposed to do tags = latest, I agreed, altho it wasn't my first idea:
- https://github.com/Taxel/PlexTraktSync/pull/413#issuecomment-892445784

i gu3ss it got lost in translation.

is the logic doable?

and if someone wants builds from "main" branch they can use "main" tag. it's considered unstable.

**Comment by chrillep** [comment]
Misunderstanding on my part. :)

> is the logic doable?

yeah it's doable. 
I believe its the default :) 

just removing 
https://github.com/Taxel/PlexTraktSync/blob/main/.github/workflows/docker-image.yml#L47-L48
should do it.

But ill test it and see

**Comment by glensc** [comment]
🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

**Pull request merged**
