### PR TITLE
Refactor: Implement shows sync using episodes

### PR DESCRIPTION
**Pull request by glensc**
Implement shows sync using episodes search:
- https://github.com/Taxel/PlexTraktSync/issues/976#issuecomment-1648004190

<del>Requires support from PlexApi side: - https://github.com/pkkid/python-plexapi/pull/1243</del>

### CODE REVIEW

**Comment by glensc** [comment]
Actually for me the syncing is even slower:
1. Using legacy TV agent
2. 30 sec (old code) vs 45 sec (new code)

reason being is that extra api calls are still there:
```
Made query /library/metadata/7632
```

**Comment by glensc** [comment]
timing again:
- this branch: Completed full sync in 2 min 9.3 seconds
- master branch: Completed full sync in 33.6 seconds

So, the new code is actually slower.

**Comment by JonnyWong16** [comment]
I think the slowdown is because it is now querying Trakt for every episode since it doesn't create the `TraktLookup` table anymore.

It's faster on the Plex side, but slower on the Trakt side.

**Comment by glensc** [comment]
I haven't verified this, but I think it's also slower now because needs to fetch every plex show separately. 

can probably can be solved by batching show fetches as well.

**Comment by glensc** [comment]
Added plex shows preloading and caching show object for next episode of same show. Timing looks promising.

scanning a library with 227 shows, 5180 episodes with hot cache. the library is mostly healthy (few missing matches) and using legacy agent. there's also bunch of reloading episode/show for year and userRating, that slows down as well.

- this branch: 12.6-13.9 seconds            
- main branch: 13.7-17.0 seconds

**Comment by glensc** [comment]
I'll go on with merge then

**Comment by simonc56** [comment]
Tested successfully.
- seems faster than before
- strange to Process each tvshows library twice

**Comment by glensc** [comment]
it's preloading tvshows in first run. do you have recommendations for it? make it silent? change display?

also, it's processing fast the first round right?

can you also post your timings of now and then?

**Comment by simonc56** [comment]
After more tests, i see no time difference between `0.28.4` and `0.28.5` when I sync ratings and watched status.
With those settings, speed is 100\~140 episodes/sec and 50\~80 movies/sec.


image


I suggest to slightly change display like that : 

image

**Comment by glensc** [comment]
what is the difference? if you made code changes so just submit them?

**Comment by simonc56** [comment]
I just draw it on paint.

image

**Pull request merged**
