### PR TITLE
Feature: Conditional library walk

### PR DESCRIPTION
**Pull request by twolaw**
Do not walk across Plex libraries if it's not needed

### CODE REVIEW

**Comment by glensc** [comment]
wouldn't it be simpler to skip calling `runner.sync` if nothing to walk? i.e then wouldn't need to add the condition in Sync class and in sync command. i.e check the state and return early in command/sync.py

**Comment by twolaw** [comment]
Nothing to walk but something to sync 😉

**Comment by glensc** [comment]
> Nothing to walk but something to sync 😉

please explain.

**Comment by twolaw** [comment]
#1019

**Pull request merged**
