### PR TITLE
Feature: Build docker image with alpine 3.17

### PR DESCRIPTION
**Pull request by twolaw**
- https://alpinelinux.org/posts/Alpine-3.17.0-released.html

### CODE REVIEW

**Comment by glensc** [comment]
@twolaw why draft?

**Comment by twolaw** [comment]
Maybe update directly to [alpine 3.18](https://alpinelinux.org/posts/Alpine-3.18.0-released.html) ?

**Comment by glensc** [comment]
> Maybe update directly to [alpine 3.18](https://alpinelinux.org/posts/Alpine-3.18.0-released.html) ?

yes

**Comment by twolaw** [comment]
Closing this PR

Substituted by :
- #1515

**Pull request closed without merging**
