### PR TITLE
Fix Plex login for users with 2FA enabled

### LINKED ISSUE #1584: PlexTraktSync is broken for Plex 2FA users
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Trying to run PTS for the first time and I'm getting a 401 unauthorized error when signing in.

### Error trace / logs

```text
> plextraktsync sync
INFO     PlexTraktSync [0.27.4]
Please enter your Plex username or e-mail (ericswpark): ericswpark
If you have 2 Factor Authentication enabled on Plex you can append the code
to your password below (eg. passwordCODE)
Please enter your Plex password:
Log in to Plex failed: '(401) unauthorized;
https://plex.tv/api/v2/users/signin <?xml version="1.0" encoding="UTF-8"?>
<errors>   <error code="1029" message="Please enter the verification code"
status="401"/> </errors> ', Try again.
```

### Expected behavior

Logging in to Plex works

### Steps to reproduce the behavior

1. Run `plextraktsync sync`
2. Type in username
3. Type in password with TOTP code

### Inspect of problematic items

_No response_

### Workarounds

_No response_

### Install method

pipx

### Config file contents

```yaml
# Config File: /Users/ericswpark/Library/Application Support/PlexTraktSync/config.yml
cache:
  path: /Users/ericswpark/Library/Caches/PlexTraktSync/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
  rating_priority: plex
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

PlexTraktSync 0.27.4

### Python Version

3.11.5

### Operating System and Version

macOS 13.5.2

### PR DESCRIPTION
**Pull request by ericswpark**
This should fix login for Plex users using 2FA.

Closes #1584 

TODO:
- [x] Test that it works
- [x] Test that commit doesn't break login for non-2FA users

### CODE REVIEW

**Comment by ericswpark** [comment]
Fixed a bug with the initial commit where the arguments were being passed to the wrong parameter^ (Blame me for being confused with Swiftlang and thinking Python did named parameter matching)

I've tested it and it works for both 2FA and non-2FA users!

**Comment by glensc** [comment]
So empty code is probably `""`, not `None`, that's fine too?

```py
code = Prompt.ask(PROMPT_PLEX_CODE)
return MyPlexAccount(username=username, password=password, code=code)
```

**Comment by ericswpark** [comment]
@glensc I'm not sure what `Prompt` returns if the user leaves it empty, but I've confirmed that it works by creating a dummy account without 2FA. Either the `plexapi` library leaves it out intelligently, or the Plex API ignores the value if 2FA is not set up.

**Comment by twolaw** [comment]
Readme file should be updated too (remove line about code appended to password).

**Comment by ericswpark** [comment]
@twolaw done, just updated it :) Please let me know if there are other references that I may have missed.

**Comment by twolaw** [comment]
Remove comment import on line 17.

**Pull request merged**
