### PR TITLE
Take guid in pre-defined order

### LINKED ISSUE #313: Unable to scrobble episodes scanned with the new TV agent
### The problem

I cannot seem to scrobble S04E01 of Dynasty. As you can see in the logs, it doesn't seem to be able to match the episode in Trakt.

```py
State: playing
Found <imdb:tt11568606:<Episode:62362:Dynasty-s04e01>>
State: paused
Found <imdb:tt11568606:<Episode:62362:Dynasty-s04e01>>
State: stopped
Found <imdb:tt11568606:<Episode:62362:Dynasty-s04e01>>
```

If I play another episode...

```py
State: playing
Found <imdb:tt6926268:<Episode:30770:Dynasty-(2017)-s01e01>>
<Episode:30770:Dynasty-(2017)-s01e01>: 0.194093% Watched: True, LastViewed: 2019-11-10 11:10:04
State: stopped
Found <imdb:tt6926268:<Episode:30770:Dynasty-(2017)-s01e01>>
<Episode:30770:Dynasty-(2017)-s01e01>: 0.194093% Watched: True, LastViewed: 2019-11-10 11:10:04
```

Note the discrepancies in the names. `Dynasty-(2017)` seems to be the correct one, whereas just `Dynasty` doesn't seem to match.

**Problematic XML**: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="xxxxx" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1618841291">
   <Video ratingKey="62362" key="/library/metadata/62362" parentRatingKey="62361" grandparentRatingKey="28869" guid="plex://episode/60859a8c188611002d692098" parentGuid="plex://season/60859a8a188611002d692087" grandparentGuid="plex://show/5d9f410dca3253001ef364c7" type="episode" title="That Unfortunate Dinner" grandparentKey="/library/metadata/28869" parentKey="/library/metadata/62361" librarySectionTitle="TV Shows" librarySectionID="2" librarySectionKey="/library/sections/2" grandparentTitle="Dynasty (2017)" parentTitle="Season 4" contentRating="TV-14" summary="Fallon and Liam plan their wedding, with some unsolicited input from Alexis. Dominique runs into hiccups with her new fashion line and turns to unexpected sources for help. Blake is determined to work on his relationship with Cristal." index="1" parentIndex="4" viewOffset="624040" lastViewedAt="1620574213" parentYear="2021" thumb="/library/metadata/62362/thumb/1620542113" art="/library/metadata/28869/art/1620542043" parentThumb="/library/metadata/62361/thumb/1620548757" grandparentThumb="/library/metadata/28869/thumb/1620542043" grandparentArt="/library/metadata/28869/art/1620542043" duration="2549248" originallyAvailableAt="2021-05-07" addedAt="1620473297" updatedAt="1620542113">'
[REDACTED]
      <Guid id="imdb://tt11568606" />
      <Guid id="tmdb://2898461" />
      <Guid id="tvdb://8311010" />
      <Extras size="0" />
      <Related />
   </Video>
</MediaContainer>
```

**XML from another episode**:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="xxxxx" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1618841291">
   <Video ratingKey="28871" key="/library/metadata/28871" parentRatingKey="28870" grandparentRatingKey="28869" guid="plex://episode/5e833825d9e2b6004236d566" parentGuid="plex://season/602e774167f4c8002ce56f48" grandparentGuid="plex://show/5d9f410dca3253001ef364c7" type="episode" title="Guilt Trip To Alaska" grandparentKey="/library/metadata/28869" parentKey="/library/metadata/28870" librarySectionTitle="TV Shows" librarySectionID="2" librarySectionKey="/library/sections/2" grandparentTitle="Dynasty (2017)" parentTitle="Season 3" contentRating="TV-14" summary="On the eve of the Carrington Foundation fundraiser, bodies are pulled from the lake on the Carrington Estate. Fallon finds herself haunted by Trixie's death in unexpected ways. Kirby visits Culhane." index="1" parentIndex="3" audienceRating="4.5" viewCount="1" lastViewedAt="1573364408" parentYear="2019" thumb="/library/metadata/28871/thumb/1618312430" art="/library/metadata/28869/art/1620542043" parentThumb="/library/metadata/28870/thumb/1620542111" grandparentThumb="/library/metadata/28869/thumb/1620542043" grandparentArt="/library/metadata/28869/art/1620542043" duration="2547808" originallyAvailableAt="2019-10-11" addedAt="1588414369" updatedAt="1618312430" audienceRatingImage="themoviedb://image.rating">
[REDACTED]
      <Guid id="imdb://tt9702234" />
      <Guid id="tmdb://1935866" />
      <Guid id="tvdb://7241394" />
      <Role id="185154" filter="actor=185154" tag="Ben Levin" role="Doug" thumb="https://metadata-static.plex.tv/people/5d776849f59e58002189b0d6.jpg" />
      <Extras size="0" />
      <Related />
   </Video>
</MediaContainer>
```

### Expected behavior

Item watched would scrobble.

### Steps to reproduce the behavior

Unsure. Maybe `touch` a file with this TV show/episode and have Plex scan it?

### Workarounds

Not that I'm aware of.

### Environment

- Version: `master`
- Python version: `3.8.5`
- Platform: Ubuntu 20.04 `aarch64`

### PR DESCRIPTION
**Pull request by glensc**
Take guid in this order:
- tmdb, tvdb, then imdb

See https://github.com/Taxel/PlexTraktSync/issues/313#issuecomment-838447631

Fixes #313

### CODE REVIEW

**Comment by twolaw** [comment]
I disagree this PR because it doesn't solve the problem.
Why did you merge without any review ?

**Comment by glensc** [comment]
> I disagree this PR because it doesn't solve the problem.

Good. Then submit your solution!

besides, you were ok with this solution:
- https://github.com/Taxel/PlexTraktSync/issues/313#issuecomment-838921486

and it does solve the problem in #313, and matches what trakt support said:
- https://github.com/Taxel/PlexTraktSync/issues/313#issuecomment-838447631

> Why did you merge without any review?

Because you have said you don't want to review if you think you have no mood. besides, people have difficulties testing code from a branch, so it's easier just to release. and you can always use an older version.

**Comment by twolaw** [comment]
You didn't give time to read you code, it was already merged 😄 
Anyway, your solution is ok for now, tmdb being the most used guid **today**.

I will find time to write and submit my solution.

**Comment by glensc** [comment]
And don't forget that I spent good amount of time writing this changeset and testing with variations.

And in my design this change was needed anyway for the next iteration. When processing multiple guids they should be in this order, not what plex returns.

**Comment by twolaw** [comment]
> When processing multiple guids they should be in this order, not what plex returns.

Why ?

**Pull request merged**
