### PR TITLE
Add documentation about watch scrobbling

### PR DESCRIPTION
**Pull request by glensc**
Documentation for https://github.com/Taxel/PlexTraktSync/pull/192

NOTE: The Trakt app may need scrobble permission:
- https://trakt.docs.apiary.io/#reference/scrobble

### CODE REVIEW

**Comment by glensc** [comment]
Not sure is the `watch` good name for the command? I used the name as it's similar to `webpack watch`, but maybe not that intuitive to end users here?

WDYT?

**Comment by glensc** [comment]
@twolaw I requested review yesterday. You don't get email notification on that?

**Comment by twolaw** [comment]
I disabled email notif.
I visit github when I want to.
I consider this as a hobby, not a job.
I may postpone some reviews or issue reading if I think it needs more time for me to understand.
It's not a problem for me if a review or an issue waits 1 or 2 or 3 weeks. 😃

**Review by twolaw — APPROVED** [review]

**Comment by glensc** [comment]
@twolaw did not get answer to question:
- https://github.com/Taxel/PlexTraktSync/pull/294#issuecomment-826522592

**Comment by twolaw** [comment]
`watch` name looks good to me.

**Pull request merged**
