### PR TITLE
Fix multi arch support 

### LINKED ISSUE #522: Add multi arch support
I've tried running the container on `arm64` but I get an exec error. 

It seems to be `amd64` only. Please add support for other architectures.

### PR DESCRIPTION
**Pull request by agneevX**
Close #522

### CODE REVIEW

**Comment by glensc** [comment]
please test this on your fork this time, adding 'on: branches: patch-6' for example

**Comment by glensc** [comment]
Wasn't the problem due to missing qemu action?

**Comment by agneevX** [comment]
Build successful: https://github.com/agneevX/PlexTraktSync/runs/3781874005?check_suite_focus=true

**Comment by agneevX** [comment]
Build successful: https://github.com/agneevX/PlexTraktSync/runs/3781874005?check_suite_focus=true

**Comment by glensc** [comment]
Built on master, but a bit slow:
- https://github.com/Taxel/PlexTraktSync/runs/3781923572?check_suite_focus=true

**Pull request merged**
