### PR TITLE
Monkey patch trakt UserList with a type field

### PR DESCRIPTION
**Pull request by glensc**
Monkey patching https://github.com/moogar0880/PyTrakt/pull/206

Fixes https://github.com/Taxel/PlexTraktSync/issues/941

### CODE REVIEW

**Comment by marksie1988** [comment]
I am just running a test now, but so far it seems to be working.

**Comment by marksie1988** [comment]
Ok i did the command `plextraktsync sync` which throws errors:

```
INFO     PlexTraktSync [0.20.10]
Sync Movie sections: [<PlexLibrarySection:movie:Films>]
Sync Show sections: [<PlexLibrarySection:show:TV programmes>]
INFO     Downloaded List Fast and Furious Chronology
INFO     Downloaded List The Matrix Franchise
INFO     Downloaded List The Bourne Identity Series
Traceback (most recent call last):
  File "/root/.local/bin/plextraktsync", line 8, in <module>
    sys.exit(cli())
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/commands/sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/sync.py", line 64, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/root/.local/pipx/venvs/plextraktsync/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: <lambda>() missing 1 required positional argument: 'type'
```

**Comment by glensc** [comment]
@marksie1988: wtf? you're not even using code from this branch, why should it work?!

**Comment by marksie1988** [comment]
> @marksie1988: wtf? you're not even using code from this branch, why should it work?!

Aren't I? I specified to install this PR with:

`plextraktsync self-update --pr 1100`

It looked to update as expected. I'll double check

**Comment by glensc** [comment]
1. your version said "INFO     PlexTraktSync [0.20.10]"
1. line numbers don't match with the code.

so I'd say you failed initially :)

**Comment by glensc** [comment]
Added debug: 54e5924b, it should give a trace to see where the recursion came from.

**Comment by glensc** [comment]
@marksie1988 I'm not familiar with the problem, what should I enable in my config.yml so I get the same error?

**Comment by marksie1988** [comment]
Copy of my config file below
```
cache:
  path: $PTS_CACHE_DIR/trakt_cache
excluded-libraries:
- Private
- Family Holidays
logging:
  append: true
  debug: false
  filename: plextraktsync.log
sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

I ran again `plextraktsync self-update --pr 1100` however the output from command `plextraktsync@1100 sync` was still the same:

```
INFO     PlexTraktSync [0.22.0dev0]                                                                                                                                                         INFO     Sync Movie sections: [<PlexLibrarySection:movie:Films>]                                                                                                                            INFO     Sync Show sections: [<PlexLibrarySection:show:TV programmes>]                                                                                                                      Error: Error running sync command: maximum recursion depth exceeded while calling a Python object
```

**Comment by glensc** [comment]
the version will stay `0.22.0dev0` regardless of the commit. try uninstalling old version first with pipx. also didn't ask for full config, but what config key actually matters.

**Comment by racincason** [comment]
I created a copy of my working directory and updated the 2 python files. 
I am also getting an error. Please see trace below. 

**I understand it says 0.22.1 branch but as i said, i updated the files manually. 

`Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USERNAME\Downloads\PlexTraktSync-0.22.1\PlexTraktSync-0.22.1 - Copy\plextraktsync\__main__.py", line 18, in <module>
    cli()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USERNAME\Downloads\PlexTraktSync-0.22.1\PlexTraktSync-0.22.1 - Copy\plextraktsync\cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "C:\Users\USERNAME\Downloads\PlexTraktSync-0.22.1\PlexTraktSync-0.22.1 - Copy\plextraktsync\commands\sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "C:\Users\USERNAME\Downloads\PlexTraktSync-0.22.1\PlexTraktSync-0.22.1 - Copy\plextraktsync\sync.py", line 83, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "C:\Users\USERNAME\Downloads\PlexTraktSync-0.22.1\PlexTraktSync-0.22.1 - Copy\plextraktsync\trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "C:\Users\USERNAME\Downloads\PlexTraktSync-0.22.1\PlexTraktSync-0.22.1 - Copy\plextraktsync\trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\trakt\core.py", line 554, in inner
    return generator.send(json_data)
  File "C:\Users\USERNAME\Downloads\PlexTraktSync-0.22.1\PlexTraktSync-0.22.1 - Copy\plextraktsync\trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\trakt\users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\trakt\users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\trakt\users.py", line 72, in __init__
    super(UserList, self).__init__()
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by glensc** [comment]
1a9c2ed6 might help

**Comment by marksie1988** [comment]
Still happening im afraid:

```
~# plextraktsync@1100 sync
INFO     PlexTraktSync [0.22.0@pr/1100#1b3625cc]                                                                                                                                            INFO     Sync Movie sections: [<PlexLibrarySection:movie:Films>]                                                                                                                            INFO     Sync Show sections: [<PlexLibrarySection:show:TV programmes>]                                                                                                                      Traceback (most recent call last):
  File "/root/.local/bin/plextraktsync@1100", line 8, in <module>
    sys.exit(cli())
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/plextraktsync/cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/plextraktsync/commands/sync.py", line 58, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/plextraktsync/sync.py", line 83, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/trakt/users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/trakt/users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "/root/.local/pipx/venvs/plextraktsync@1100/lib/python3.9/site-packages/trakt/users.py", line 72, in __init__
    super(UserList, self).__init__()
  [Previous line repeated 980 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by glensc** [comment]
The trace indicates that `liked_lists` must be enabled in `config.yml`:
- https://github.com/Taxel/PlexTraktSync/blob/5c2c373f3144eafffe3a8eca6e5335d1b499cc11/plextraktsync/sync.py#L81-L83

i.e trying to figure out how to reproduce this:
- https://github.com/Taxel/PlexTraktSync/pull/1100#issuecomment-1279705151

**Comment by glensc** [comment]
That is still not enough to reproduce:
> `[2022-10-19 16:22:10] INFO     Completed full sync in 1 min 13.8 seconds`

if any of you want me to work on this, provide the exact steps to reproduce!

**Comment by marksie1988** [comment]
All I have done is as follows: 

Run command:
```
plextraktsync self-update --pr 1100
plextraktsync@1100 sync
```
After this the failure occurs, i'm using the config that I posted previously. 

not sure you need it, but Plex server is Version `1.29.1.6313`
Server is running Debian 11 

im not too familiar with pipx so unsure if its configuration could impact the venv configurations.

**Comment by racincason** [comment]
here's the latest error with your latest branch. I'm running on windows. I'm about to try your branch with PIP on WSL. I'll let you know if i get the same error. 

Thanks again for all your work trying to resolve this for the community. 

`WARNING  No git dir found
INFO     PlexTraktSync [0.22.0dev0]
INFO     Sync Movie sections: [<PlexLibrarySection:movie:Movies>]
INFO     Sync Show sections: [<PlexLibrarySection:show:Kids>, <PlexLibrarySection:show:TV Shows>]
Traceback (most recent call last):
  File "C:\Users\USER\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\__main__.py", line 18, in <module>
    cli()
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\cli.py", line 47, in cli
    sync()
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\commands\sync.py", line 57, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\sync.py", line 83, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "C:\Users\USER\Python\Python310\lib\site-packages\trakt\core.py", line 554, in inner
    return generator.send(json_data)
  File "C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\plextraktsync\trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
  File "C:\Users\USER\Python\Python310\lib\site-packages\trakt\users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "C:\Users\USER\Python\Python310\lib\site-packages\trakt\users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "C:\Users\USER\Python\Python310\lib\site-packages\trakt\users.py", line 72, in __init__
    super(UserList, self).__init__()
  [Previous line repeated 970 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
PS C:\Users\USER\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af\PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af>`

**Comment by racincason** [comment]
Running in Bash :

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/cli.py", line 47, in cli
    sync()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/commands/sync.py", line 57, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/sync.py", line 83, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "/home/USER/.local/lib/python3.8/site-packages/trakt/core.py", line 554, in inner
    return generator.send(json_data)
  File "/mnt/c/temp/PlexTraktSync/PlexTraktSync-7f781681aed2c9ce5622b8f6e1a6259454fea7af/plextraktsync/trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
  File "/home/USER/.local/lib/python3.8/site-packages/trakt/users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "/home/USER/.local/lib/python3.8/site-packages/trakt/users.py", line 72, in __init__
    super(UserList, self).__init__()
  File "/home/USER/.local/lib/python3.8/site-packages/trakt/users.py", line 72, in __init__
    super(UserList, self).__init__()
  [Previous line repeated 970 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by glensc** [comment]
Replaced with https://github.com/Taxel/PlexTraktSync/pull/1124

**Comment by glensc** [comment]
@racincason stop abusing the pull requests, create new issue of your problems!

**Pull request closed without merging**
