### PR TITLE
Search all guids for a match

### PR DESCRIPTION
**Pull request by glensc**
**IMPORTANT**: This changeset bumps Python minimum version to 3.7:
- https://github.com/Taxel/PlexTraktSync/pull/336

NOTE: searching multiple guids requires to use of the new agent.

Future todo: 
- cleanup old unused methods
- cleanup proxy methods to guid on PlexMediaItem

refs:
- https://github.com/Taxel/PlexTraktSync/issues/318

### CODE REVIEW

**Comment by glensc** [comment]
I've slightly tested this locally with a legacy agent.

I've also noticed movies scan went slower: 6.2s -> 1m 38.7s, shows: 8.1s -> 13.6s, this is after eda9103 commit.

My guess is that now it has to parse all guids, even if needs one guid.

**Comment by glensc** [comment]
The slowness was mitigated with 8143ca3, but I don't like having support old code too, makes codebase complicated.

**Comment by glensc** [comment]
@twolaw so when I request a review, you don't even beep for 4 days.

**Comment by glensc** [comment]
I like the GUID abstraction here, as appears most of the logic we do is on GUID value rather on the full Plex Media Item.

But I don't know why the new code makes things slower. probably iterating over .guids rather than reading single .guid makes more plex requests that slows things down. should compare log file with debug enabled to confirm.

Currently, we don't cache plex requests at all. We should look into doing that. I've done some research, and some refactoring needed again:
- https://github.com/reclosedev/requests-cache/issues/260

also, I think we should not build too much logic due to trakt.tv being broken, but rather help trakt.tv to fix their issues and data.

**Review by twolaw — APPROVED** [review]

**Pull request merged**
