### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Geezus42**
`docker-compose` --> `docker compose`

The name of the command has changed.

### CODE REVIEW

**Comment by glensc** [comment]
1. clickbait. pr title should describe the changes
2. both commands should be supported. so this is no-go

**Comment by Geezus42** [comment]
Both commands are not supported unless you have aliases. If you run `docker-compose` on a system without aliases, it will tell you the command does not exist. I understand some distros/installers may include the alias by default, but it is stop gap that should be phased out since the command syntax has been changed.

**Comment by Geezus42** [comment]
Both commands are not supported unless you have aliases. If you run `docker-compose` on a system without aliases, it will tell you the command does not exist. I understand some distros/installers may include the alias by default, but it is stop gap that should be phased out since the command syntax has been changed.

**Comment by Geezus42** [comment]
There fixed the title.

**Pull request closed without merging**
