### PR TITLE
Refactor: Use TVShow.episodes property for episodes trakt id lookup

### PR DESCRIPTION
**Pull request by glensc**
Requires:
- https://github.com/moogar0880/PyTrakt/pull/176

### CODE REVIEW

**Comment by twolaw** [comment]
⚠️ this PR breaks `TraktLookup` functionnality, do not release as is

**Comment by glensc** [comment]
perhaps explain the problem? steps to reproduce?

**Comment by twolaw** [comment]
Just sync a show (i tested Attack on Titan) and see that `find_by_guid` is called for each episode.
With `0.23.3` there is no `find_by_guid` called because the lookup table works.

**Comment by glensc** [comment]
Unable to reproduce, which season/episode is failing? 

I added s01e01 test:
- https://github.com/Taxel/PlexTraktSync/pull/1129

just to be sure:
1. you installed required dependencies?
2. you cleared cache so it's not related to cache problem?

**Comment by twolaw** [comment]
I found the problem.

The seasons() from trakt.tv.py uses `extract_ids()` to flatten the ids dict so the `te.ids.get(guid.provider)` doesn't work anymore, it always return None.

`te.ids.get(guid.provider)` needs to be replaced by `getattr(te, guid.provider)`

**Comment by glensc** [comment]
Found the problem:
- [`17abf87` (#1129)](https://github.com/Taxel/PlexTraktSync/pull/1129/commits/17abf87ca610164ce699bc26a11afa9f6e42ef30)

**Comment by glensc** [comment]
So, perhaps the PR was incomplete:
- https://github.com/moogar0880/PyTrakt/pull/176/files

should add extract_ids to the `seasons()` method?

but you seem to claim opposite it does extract_ids while I see it doesn't do extract_ids

**Comment by twolaw** [comment]
I think we should use `extract_ids()` everywhere in pytrakt to be consistent with moogar0880 code.

**Comment by glensc** [comment]
> I think we should use extract_ids() everywhere in pytrakt to be consistent with moogar0880 code.

agree, as without that, properties like `ids` would return `None` for all providers.  `extract_ids` missing, is bug.

**Pull request merged**
