### PR TITLE
Feature: Add install from pull request instructions

### PR DESCRIPTION
**Pull request by glensc**
See https://github.com/pypa/pipx/issues/812#issuecomment-1066684085

### CODE REVIEW

**Comment by glensc** [comment]
@tony saw your [comment](https://github.com/pypa/pipx/issues/812#issuecomment-1066684085). can you help out?

This project isn't installable even when using an existing tag or branch:

```
$ pipx install --suffix=@pr git+https://github.com/Taxel/PlexTraktSync@0.18.21
```

<details>

```
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
          req = REQUIREMENT.parseString(requirement_string)
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
          raise exc
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
          loc, tokens = self._parse( instring, 0 )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
          loc, exprtokens = e._parse( instring, loc, doActions )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
          return self.expr._parse( instring, loc, doActions, callPreParse=False )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
          loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
          raise ParseException(instring, loc, self.errmsg, self)
      pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/glen/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/glen/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/glen/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 1, in <module>
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 122, in setup
          dist.parse_config_files()
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/declarative_requirements/integration.py", line 104, in wrapper
          dist._finalize_requires()
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 546, in _finalize_requires
          self._move_install_requirements_markers()
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 585, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3089, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/pip-build-env-oqa9xf46/overlay/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
          raise InvalidRequirement(
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'-i https'": Expected W:(abcd...)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Cannot determine package name from spec 'git+https://github.com/Taxel/PlexTraktSync@0.18.21'. Check package spec for
errors.
```
</details>

what could be missing/wrong? and how to solve?

**Comment by glensc** [comment]
Ok, now can install from branch:

```
➜ pipx install --suffix=@pr 'git+https://github.com/Taxel/PlexTraktSync@pipx-installable'
⣽ installing PlexTraktSync from spec 'git+https://github.com/Taxel/PlexTraktSync@pipx-installable'
  installed package PlexTraktSync 0.18.0.dev0 (PlexTraktSync@pr), installed using Python 3.10.2
  These apps are now globally available
    - plextraktsync@pr
done! ✨ 🌟 ✨
```

**Comment by tony** [comment]
If you got it working that's excellent @glensc.  That was the first time I've customized the command

**Comment by twolaw** [comment]
Can this PR be merged ?

**Comment by glensc** [comment]
it's not complete, currently contains a hack that should not be merged:
- ca31725705e86d2e357991d3919073dc92acfc1e

for it, a fix is proposed, but not merged:
- https://github.com/s0undt3ch/setuptools-declarative-requirements/pull/7

**Comment by glensc** [comment]
Added `plextraktsync self-update --pr 838` usage as well:

```
✖  plextraktsync self-update --pr 838
Updating PlexTraktSync to the pull request #838 version using pipx
⣻ determining package name from 'git+https://github.com/Taxel/PlexTraktSync@refs/pull/838/head'
Installing to existing venv 'PlexTraktSync@838'
⣟ installing PlexTraktSync from spec 'git+https://github.com/Taxel/PlexTraktSync@refs/pull/838/head'
  installed package PlexTraktSync 0.20.0.dev0 (PlexTraktSync@838), installed using Python 3.10.5
  These apps are now globally available
    - plextraktsync@838
done! ✨ 🌟 ✨
```

**Pull request merged**
