### PR TITLE
Add cache entries for trakt search

### PR DESCRIPTION
**Pull request by glensc**
these seem to be left out from provided config. found them in my local config.

### CODE REVIEW

**Review by simonc56 — APPROVED** [review]

**Comment by glensc** [comment]
i was wondering what was previous behavior. haven't looked into that yet

**Comment by glensc** [comment]
not sure. no-cache was previous behavior?

```diff
 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie
 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie
 DEBUG[requests_cache.policy.actions]:Cache directives from request headers: CacheDirectives()
+DEBUG[requests_cache.policy.expiration]:URL https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie matched pattern "*.trakt.tv/search/imdb/tt*?type=movie": 1 day, 0:00:00
 DEBUG[requests_cache.policy.actions]:Pre-read cache checks: Passed
-DEBUG[requests_cache.policy.actions]:Post-read cache actions: CacheActions(expire_after=-1, send_request=True)
-DEBUG[urllib3.connectionpool]:https://api-v2launch.trakt.tv:443 "GET /search/imdb/tt0426552?type=movie HTTP/1.1" 200 None
-DEBUG[requests_cache.policy.actions]:Cache directives from response headers: CacheDirectives(expires='Fri, 05 Jan 2024 22:05:08 GMT', max_age=28800, etag='W/"9ab5ea5796f7bd9d2a607fd331df873e"')
-DEBUG[requests_cache.policy.actions]:Pre-write cache checks: Passed
-DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie): <Response [200]>
+DEBUG[requests_cache.policy.actions]:Post-read cache actions: CacheActions(expire_after=datetime.timedelta(days=1))
+DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie): <CachedResponse [200]: created: 2024-01-05 16:05:08 EET, expires: 2024-01-06 00:05:08 EET (fresh), size: 2 bytes, request: GET https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie>
```

**Comment by glensc** [comment]
trakt headers

```
➜ ./trakt-api.sh 'https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie' -i
HTTP/2 200 
date: Fri, 05 Jan 2024 14:28:37 GMT
content-type: application/json; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
x-pagination-page: 1
x-pagination-limit: 10
expires: Fri, 05 Jan 2024 22:05:08 GMT
x-pagination-page-count: 0
x-pagination-item-count: 0
cache-control: public, max-age=28800
vary: Accept-Encoding
etag: W/"9ab5ea5796f7bd9d2a607fd331df873e"
x-request-id: a11c87f9-f8df-4df1-a1f2-2c2f72a7d61e
x-runtime: 0.011312
cf-cache-status: HIT
age: 1409
server: cloudflare
cf-ray: 840c68a5fd2cd987-HEL
alt-svc: h3=":443"; ma=86400

[]
```

**Comment by glensc** [comment]
main branch with empty cache

```
PlexTraktSync(main) ➜ ./cache.sh  'https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie'
// <CachedResponse [200]: created: 2024-01-05 16:29:52 EET, expires: 2024-01-06 00:29:52 EET (fresh), size: 2 bytes, request: GET https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie>
// Date: Fri, 05 Jan 2024 14:29:52 GMT
// Content-Type: application/json; charset=utf-8
// Transfer-Encoding: chunked
// Connection: keep-alive
// x-frame-options: SAMEORIGIN
// x-xss-protection: 0
// x-content-type-options: nosniff
// x-download-options: noopen
// x-permitted-cross-domain-policies: none
// referrer-policy: strict-origin-when-cross-origin
// x-pagination-page: 1
// x-pagination-limit: 10
// expires: Fri, 05 Jan 2024 22:05:08 GMT
// x-pagination-page-count: 0
// x-pagination-item-count: 0
// Cache-Control: public, max-age=28800
// vary: Accept-Encoding
// Content-Encoding: gzip
// etag: W/"9ab5ea5796f7bd9d2a607fd331df873e"
// x-request-id: a11c87f9-f8df-4df1-a1f2-2c2f72a7d61e
// x-runtime: 0.011312
// CF-Cache-Status: HIT
// Age: 1484
// Server: cloudflare
// CF-RAY: 840c6a79e8a2d999-HEL
// alt-svc: h3=":443"; ma=86400
[]
```

this branch, empty cache

```

PlexTraktSync(search-cache) ✖ ./cache.sh  'https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie'                          
// <CachedResponse [200]: created: 2024-01-05 16:37:33 EET, expires: 2024-01-06 00:37:33 EET (fresh), size: 2 bytes, request: GET https://api-v2launch.trakt.tv/search/imdb/tt0426552?type=movie>
// Date: Fri, 05 Jan 2024 14:37:33 GMT
// Content-Type: application/json; charset=utf-8
// Transfer-Encoding: chunked
// Connection: keep-alive
// x-frame-options: SAMEORIGIN
// x-xss-protection: 0
// x-content-type-options: nosniff
// x-download-options: noopen
// x-permitted-cross-domain-policies: none
// referrer-policy: strict-origin-when-cross-origin
// x-pagination-page: 1
// x-pagination-limit: 10
// expires: Fri, 05 Jan 2024 22:05:08 GMT
// x-pagination-page-count: 0
// x-pagination-item-count: 0
// Cache-Control: public, max-age=28800
// vary: Accept-Encoding
// Content-Encoding: gzip
// etag: W/"9ab5ea5796f7bd9d2a607fd331df873e"
// x-request-id: a11c87f9-f8df-4df1-a1f2-2c2f72a7d61e
// x-runtime: 0.011312
// CF-Cache-Status: HIT
// Age: 1945
// Server: cloudflare
// CF-RAY: 840c75bce9d34c8a-HEL
// alt-svc: h3=":443"; ma=86400
[]
```

result no difference.

**Comment by glensc** [comment]
merging anyway to keep things consistent

**Pull request merged**
