### PR TITLE
Add --batch-size option for TraktBatch

### PR DESCRIPTION
**Pull request by glensc**
```
Usage: main.py sync [OPTIONS]

  Perform sync between Plex and Trakt

Options:
  --show TEXT             Sync specific show only
  --sync [all|movies|tv]  Specify what to sync  [default: all]
  --batch-size INTEGER    Batch size for collection submit queue  [default: 1]
  --help                  Show this message and exit.
```

refs:
- https://github.com/Taxel/PlexTraktSync/pull/232#issuecomment-821866092
- https://github.com/Taxel/PlexTraktSync/issues/256#issuecomment-821851004

### CODE REVIEW

**Comment by glensc** [comment]
@BEisem you can use --batch-size=1 to submit queue immediately.

I have not tested at all this code, will test later. But if you wish you can test and leave your feedback.

**Comment by twolaw** [comment]
In help command can you tell the unit of batch size ? is it kB ?

**Comment by glensc** [comment]
@twolaw it is amount.

**Comment by glensc** [comment]
@twolaw please help to rephrase it. in my opinion, it's clear already: "Specify batch size for collection submit queue"

**Comment by BEisem** [comment]
Ok so if I set it to `--batch-size=10` it will collect 10 items before sending it to Trakt? That works... (haven't had a chance to test this yet, will do so shortly)

**Comment by twolaw** [comment]
Ok why would the average user need to access this variable and change it? and how could one know what a good batch-size value is ?
I may be wrong but I think this is internal setting just like trakt_post_delay.

**Comment by BEisem** [comment]
Actually I like the idea of having the option available to users. This way each user can choose their own "risk/reward" ... risk of losing entries with a higher amount, but fewer API calls... and lower risk with a lower number, but at the expense of higher API usage.

Maybe whatever is decided to be the best option can be the default, and it will only change from that if the user adds `-batch-size=` in the config file.

I set it to `batch-size=10` and I'm currently going through my movie library ... it's the first time in 2 days that I'm getting entries in my Trakt account, since previously it was crashing and not making it all the way through. I also like that it shows a status update every time it adds to the collection: `INFO: Updated Trakt collection: {'added': {'movies': 10}}`

I still think "Add to Trakt Collection:" should be changed to something like "Added to queue" or "Added to batch" to be more clear. But this is a great step in the right direction!

**Comment by twolaw** [comment]
> Actually I like the idea of having the option available to users. This way each user can choose their own "risk/reward" ... risk of losing entries with a higher amount, but fewer API calls... and lower risk with a lower number, but at the expense of higher API usage.

I disagree. IMHO this should not be in user settings.
You spent time to read the code and understand it so this setting makes sense to you.
But do not forget the [average user](https://en.wikipedia.org/wiki/KISS_principle) who will not understand this risk/reward thing about API calls and would say : "_I don't care, just make the sync work_"

----

I agree with you about the logs.
And another solution is to log all items of the batch only when the batch is successfully sent : "Add to Trakt Collection: <Movie1> <Movie2> <Movie3> <Movie4> <Movie5>"

**Comment by glensc** [comment]
`--batch-size` option is not for average users. It's for advanced users who understand what is batching and what would it improve.

And the default should be `1`, so by default the submit would be slow, but accurate.

The solution would be to make batching logic smarter:
- https://github.com/Taxel/PlexTraktSync/pull/232#issuecomment-821870284

**Comment by glensc** [comment]
linguistically `Add to Trakt Collection` is correct, as it doesn't say "Added", but "Add", which means adding, but doesn't say "when" :D

When the batch is submitted, there is a message, it cames from Trakt itself, so I would leave it as is:
- https://github.com/Taxel/PlexTraktSync/pull/232

Changing the other message for now to `To be added to collection`.

**Comment by twolaw** [comment]
> The solution would be to make batching logic smarter
> 

Here is a smart solution :
By default, it should flush the batch on a time base. Let's say the trakt limit is 1sec between each, we add 0.5sec as a security delay and send batch every 1.5sec
If trakt changes its limit in the future, the script will adapt automatically.
It is better than sending 1 by 1 with a useless 1.1s delay.

**Comment by glensc** [comment]
@twolaw if you had clicked the link, it described there the exact same logic.

**Comment by glensc** [comment]
also, do note that the default POST delay does not bother typical use cass. i.e when you run sync periodically, you add 1-2 movies shows at time. and it's not that much to sleep some seconds between them. it cames relevant if you clear your trakt collection, or run the script for the first time.

**Comment by glensc** [comment]
I'm going to merge this as it is now. It restores previous behavior (before 0.7.9 #232), and if someone wants faster initial sync. they can now use --batch-size=100 or the like.

**Pull request merged**
