### PR TITLE
Allow liked lists to sync without watchlist sync

### LINKED ISSUE #1182: Feature request: Allow syncing of Liked Lists without needing Watchlist sync
### Feature description
For the moment the Liked List sync feature (`trakt_to_plax["liked_lists"]`) is broken because it only runs if you enable the `trakt_to_plex["watchlist"]` and `trakt_to_plex["watchlist_as_playlist"]` configs.
[See here ](https://github.com/Taxel/PlexTraktSync/issues/1177#issuecomment-1309335976) for more elaborate explanation.

Syncing Liked Lists should be possible even if the `watchlist` and `watchlist_as_playlist` configs are false. 

### Use case

I don't want to sync my Trakt Watchlist as a separate Plex Playlist, but as the Plex Watchlist, yet also want to sync my Trakt Liked Lists as Plex Playlists.
For the moment this is not possible. 

### Workarounds

Leave `trakt_to_plex["watchlist"]` and  `trakt_to_plex["watchlist_as_playlist"]` on `true`

### Plan to implement

N/A

### PR DESCRIPTION
**Pull request by NGDM**
PR for Feature request: Allow syncing of Liked Lists without needing Watchlist sync.

Resolves #1182

### CODE REVIEW

**Comment by NGDM** [comment]
@glensc I did a thing.  
I think this should fulfill the feature request. 

Was pretty easy with the github.dev tool 👍

Let me know if this needs anything else.

**Comment by glensc** [comment]
image


you should never create PR from your default branch. you will run into issues if the branches diverge or you want to add other commits to your default branch not related to this PR. all commits you add to your `main` branch end up here until this PR is open.

**Comment by glensc** [comment]
Rewrote the commits, because I follow atomic commits:
- https://www.freshconsulting.com/insights/blog/atomic-commits/

**Comment by glensc** [comment]
"git rebase" is the search keyword. as long as commits are not merged to the default branch, it's acceptable (and common practice) to rewrite commits to be better before the merge.

**Pull request merged**
