### PR TITLE
Update trakt to 3.4.2

### PR DESCRIPTION
**Pull request by glensc**
Fixes https://github.com/Taxel/PlexTraktSync/issues/941

### CODE REVIEW

**Comment by racincason** [comment]
23.2 error trace

`Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\__main__.py", line 18, in <module>
    cli()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\cli.py", line 53, in cli
    sync()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\cli.py", line 24, in wrap
    module = importlib.import_module(f".commands.{name}", package=__package__)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\commands\sync.py", line 5, in <module>
    from plextraktsync.commands.login import ensure_login
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\commands\login.py", line 5, in <module>
    from plextraktsync.commands.trakt_login import (has_trakt_token,
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\commands\trakt_login.py", line 10, in <module>
    from plextraktsync.trakt_api import TraktApi
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\trakt_api.py", line 21, in <module>
    from plextraktsync.decorators.retry import retry
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.2\PlexTraktSync-0.23.2\plextraktsync\decorators\retry.py", line 6, in <module>
    from trakt.errors import BadResponseException, TraktInternalException
ImportError: cannot import name 'BadResponseException' from 'trakt.errors' (C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\trakt\errors.py)`

**Comment by racincason** [comment]
Config File

`cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Puerneau


config:
  dotenv_override: true

plex:
  timeout: 30

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: false
  filename: plextraktsync.log

sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false

watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true

xbmc-providers:
  movies: imdb
  shows: tvdb

# vim:ts=2:sw=2:et
`

**Comment by racincason** [comment]
i re-ran the setup file, and it looks like it's working now!!! I think i had missing python components it grabbed during the setup. 10/10 man. Thanks so much for all your hard work.

**Comment by glensc** [comment]
@racincason stop hijacking random threads. bug reports must be created as new issues. I am removing your posts from here.

**Pull request merged**
