### PR TITLE
Fix config initialization recursive loop on first run

### PR DESCRIPTION
**Pull request by glensc**
This is needed for to reload .env again.

Fixes https://github.com/Taxel/PlexTraktSync/issues/153, https://github.com/Taxel/PlexTraktSync/issues/154

### CODE REVIEW

**Comment by glensc** [comment]
@Remnence @gorgarp: can you test this?

**Comment by dazedcrazy** [comment]
I tested this and still stuck in a loop.

**Comment by Remnence** [comment]
The save function doesn't actually write anything but the initial comment to the .env file.

**Comment by glensc** [comment]
Ah, I see, misread the problem. and lack of testing.

Try now with a43c440

----

Note to self:
```python
#!/usr/bin/env python3

from plex_trakt_sync.config import CONFIG


def test_env_update():
    CONFIG['PLEX_USERNAME'] = 'test'
    assert CONFIG['PLEX_USERNAME'] == '-', "Should be test"


# https://realpython.com/python-testing/
if __name__ == "__main__":
    test_env_update()
    print("Everything passed")

```

**Comment by dazedcrazy** [comment]
> Try now with [a43c440](https://github.com/Taxel/PlexTraktSync/commit/a43c4403367ce62130ab98dc6164bf7790c55ee1)

This works for me now. Thank you.

**Comment by gorgarp** [comment]
Sadly, a43c440 did not resolve the issue for me.

image

**Comment by glensc** [comment]
@gorgarp and what are your `.env` contents (be sure to remove values before sharing)? and show full output (obfuscate values before sharing).

**Comment by gorgarp** [comment]
@glensc  Good news / bad news!

Bad news, I'm an idiot and pulled from the wrong branch on my last attempt.
Good news, the fix worked!

Should  be good for merge. Thanks very much.

**Comment by glensc** [comment]
@gorgarp great then!

however, I can't merge, needs @twolaw or @Taxel approval.

**Review by twolaw — APPROVED** [review]

**Pull request merged**
